### ISSUE TITLE
Getting negative values for t_done with angularjs plugin

### ISSUE THREAD

**Issue by rajamadhavan** [SOASTA/boomerang#100]
Hi,
I am using boomerangjs with angular plugin. My build includes rt, bw and angular plugins. The version is latest from git. For specific angular soft navigation changes, i am getting t_done as negative on the beacon received back. Please find below one of the events converted to key/value pairs. Its not always but only for specific soft navigation urls. I am using it from a local browser, so i know the response is fairly quick but don't understand how it can be negative.

```
Mon Jul 25 11:11:53 2016 : rt_start=manual v=0.9 vis_st=visible ua_plt=Linux_x86_64 ua_vnd=Google_Inc. bw=44368532 bw_err=24730676.15 lat=13 lat_err=6.96 bw_time=1469425309 nu=http://127.0.0.1/app/xxxxx/xxxxxxx rt_tstart=1469425312313 rt_bstart=1469425305236 rt_end=1469425304810 t_done=-7503 r=http://127.0.0.1/XYZ u=http://127.0.0.1/app/xxxxx/xxxxxxx-*?_g_(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fw,mode:quick,to:now%2Fw))&_a_(tab:indexedFields) http_initiator=spa
```
I would like to understand on what conditions, t_done can get back a negative value? I am seeing this behaviour only while using it with angular plugins.

Thanks
-Raja

**Comment by bluesmoon** [comment]
Is this the entire beacon?  Can you show us what gets sent from dev tools?

**Comment by rajamadhavan** [comment]
This is from apache forensic log of a sample request as received from the beacon.

```
GET /cgi-bin/beaconang.pl?rt.start=manual&v=0.9&vis.st=visible&ua.plt=Linux%2520x86_64&ua.vnd=Google%2520Inc.&vis.lv=38080&vis.lh=41350&nu=http%253A%252F%252F127.0.0.1%252Fapp%252Fkibana%2523%252Fsettings%252Findices%252Funet-boomjs-*&rt.tstart=1469179218136&rt.bstart=1469177242496&rt.end=1469177241990&t_done=-1976146&r=http%253A%252F%252F127.0.0.1%252Funet&u=http%253A%252F%252F127.0.0.1%252Fapp%252Fkibana%2523%252Fsettings%252Findices%252Funet-boomjs-*%253F_g%253D(refreshInterval%253A(display%253AOff%252Cpause%253A!f%252Cvalue%253A0)%252Ctime%253A(from%253Anow-15m%252Cmode%253Aquick%252Cto%253Anow))%2526_a%253D(tab%253AindexedFields)&http.initiator=spa 
```

Thanks
-Raja

**Comment by andreas-marschke** [comment]
@rajamadhavan Hey! 

Can you validate that you are seeing this issue when you build off of the branch referenced in this pull request: https://github.com/SOASTA/boomerang/pull/98 

If my memory serves me correctly we've seen a similar issue before and fixed it. Would love to know if you can validate.

Cheers,

Andreas.

**Comment by rajamadhavan** [comment]
Hi Andreas
  Thanks for the lead. I built it after checking out fresh from the branch soasta-2016-q2. I dont see negative values in t_done anymore for the same url. 



```
raja@local:~/GIT3/boomerang$ git branch
* soasta-2016-q2
raja@local:~/GIT3/boomerang$ git config -l
remote.origin.url=https://github.com/SOASTA/boomerang.git
remote.origin.fetch=+refs/heads/soasta-2016-q2:refs/remotes/origin/soasta-2016-q2
branch.soasta-2016-q2.remote=origin
branch.soasta-2016-q2.merge=refs/heads/soasta-2016-q2


+V5cBon8AAQEAAClukZkAAABF|GET /cgi-bin/beaconang.pl?v=%2525boomerang_version%2525&vis.st=visible&ua.plt=Linux%2520x86_64&ua.vnd=Google%2520Inc.&bw=34441206&bw_err=34214590.71&lat=8&lat_err=4.24&bw_time=1469513756&bw_debug=2_4&nu=http%253A%252F%252F127.0.0.1%252Fapp%252Fkibana%2523%252Fsettings%252Findices%252Funet-boomjs-*&rt.start=manual&rt.tstart=1469514144833&rt.bstart=1469513752002&rt.end=1469514145158&t_done=325&t_other=boomerang%257C394156%252Cboomr_fb%257C-392831&r=http%253A%252F%252F127.0.0.1%252Funet&u=http%253A%252F%252F127.0.0.1%252Fapp%252Fkibana%2523%252Fsettings%252Findices%252Funet-boomjs-*%253F_g%253D(refreshInterval%253A(display%253AOff%252Cpause%253A!f%252Cvalue%253A0)%252Ctime%253A(from%253Anow%25252Fw%252Cmode%253Aquick%252Cto%253Anow%25252Fw))%2526_a%253D(tab%253AindexedFields)&http.initiator=spa&vis.lv=3240&vis.lh=98835 
```

For now, this will do for me. I will keep checking for it to be fixed in master. 


Thanks
-Raja

**Comment by nicjansma** [comment]
Great to hear Raja

**Comment by EfratGordon** [comment]
I get a negative value for t_done when using:

BOOMR.subscribe("before_beacon",
    function(o) {
        alert("This page took " + o.t_done + "ms to load");
});

The version is latest from git.
Is there any solution?
