### ISSUE TITLE
How about beacon API for tracking?

### ISSUE THREAD

**Issue by samarpanda** [SOASTA/boomerang#102]
## [Using beacon API](http://caniuse.com/#feat=beacon)

How about [beacon API](http://caniuse.com/#feat=beacon) for tracking?

![screen shot 2016-08-07 at 5 46 59 pm](https://cloud.githubusercontent.com/assets/802163/17462327/04510b7a-5cc7-11e6-9bee-c9131d567dc1.png)

**Comment by bluesmoon** [comment]
We've looked at this several times. There are limitations that make it less
useful for us and we need to fallback for unsupported browsers anyway.

**Comment by bluesmoon** [comment]
@nicjansma is looking into this now.

**Comment by nicjansma** [comment]
We're currently testing using `sendBeacon()` as part of another change, but it should end up in boomerang.js shortly.

One issue we've found was https://bugs.chromium.org/p/chromium/issues/detail?id=711060, which makes verifying it in our tests hard, but shouldn't affect the actual performance.

I've trolled the other crbugs to make sure that there aren't any other major concerns about using `sendBeacon()`, and haven't found anything of concern.  I believe GA and others are using it too.

So once these changes are approved, we will merge `sendBeacon()` support in.

**Comment by tollmanz** [comment]
@nicjansma I'm curious if you ran into any other issues with `navigator.sendBeacon()`. It does not appear that Boomerang is using it yet. Did you hit some other issues?

I'd be interested in working on this if you haven't had a chance to do so.

**Comment by bluesmoon** [comment]
I think it's part of a pending merge. We've had some success with it.

**Comment by tollmanz** [comment]
@bluesmoon Thanks for the update! I look forward to the merge.

**Comment by nicjansma** [comment]
Will try to get everything backported within the next month!

**Comment by bluesmoon** [comment]
fixed by #188
