### ISSUE TITLE
auto_xhr problems with SPA

### ISSUE THREAD

**Issue by waldbaerkoch** [SOASTA/boomerang#105]
I have an SPA and want to use auto_xhr for tracking. The HTML `head`contains:

``` html
    <script src="boomerang.js" type="text/javascript"></script>
    <script src="plugins/rt.js" type="text/javascript"></script>
    <script src="plugins/auto_xhr.js" type="text/javascript"></script>
    <script type="text/javascript">
BOOMR.init({
  beacon_url: SOME_URL,
  instrument_xhr: true
});
    </script>
```

When a user clicks on an `a` element or submits a `form`, an XHR is sent, the HTML content is changed after the response is received.
So there are two calls of `MutationHandler.prototype.addEvent()`:
1. by the `click` listener registered in `instrumentClick()`,
2. by `loadFinished()` called if `req.readyState === 4`.

In the first call

``` js
                this.setTimeout(50, index);
```

 is called, the second call aborts in

``` js
        if (last_ev) {
            if (last_ev.type === "click") {
                // 3.1 & 3.3
                if (last_ev.nodes_to_wait === 0 || !last_ev.resource.url) {
                    this.pending_events[i] = undefined;
                    return null;    // abort
                }
                // last_ev will no longer receive watches as ev will receive them
                // last_ev will wait fall interesting nodes and then send event
            }
```

When the MutationObserver observes the content changes, `MutationHandler.prototype.mutation_cb()` is called; but it aborts in

``` js
        if (index < 0 || !this.pending_events[index]) {
            // Nothing waiting for mutations
            return true;
        }
```

before

``` js
            this.setTimeout(SPA_TIMEOUT, index);
```

is reached.

Can someone please explain whether this is intended?

When the user uses browser back or forward, it looks fine, as no prior `click` event occured.

**Comment by nicjansma** [comment]
@waldbaerkoch Sorry it's taken so long for us to look at this.

Do you happen to have a repro page that we could look at?

I think the issue may be in `addEvent`, where we `return null;// abort`.  If I'm correct, what the code is doing is cancelling the click event, and not creating an XHR event.  I think we shouldn't be returning there.

**Comment by pinna72** [comment]
Hi all,

I'm facing too the same problem reported by @waldbaerkoch. Are there updates about this?

Thank you 
Antonio

**Comment by waldbaerkoch** [comment]
@nicjansma I did this test some months ago while evaluating boomerang. Unfortunately, I don't have the time to re-create the test case. Maybe pinna72 can help.

**Comment by nicjansma** [comment]
We have a fix for this being tested, and will backport after it's ready.
