### ISSUE TITLE
Possible to add an HTTP Header Authentication?

### ISSUE THREAD

**Issue by tmartin14** [SOASTA/boomerang#106]
If I want boomerang.js to send it's data to a beacon that requires an authentication token, is that possible?

**Comment by bluesmoon** [comment]
If this uses the standard `WWW-Authenticate` header, then you can set your url to `http://username:password@hostname.domain/path`

If you require a different auth header, then you'll only be able to do it with XHR beacons, and you'll have to hack boomerang to add it in.

**Comment by tmartin14** [comment]
Thanks for the quick reply.   I'm looking for token-based authentication (and realize all of the necessary precautions required with this in the source code), so it looks like I'll have to go hacking ;-).

**Comment by sridharangopal** [comment]
I was looking to do the same thing ... trying to send the data to Splunk.
Eg:
curl -k  https://localhost:8088/services/collector/raw?channel=934793C0-FC91-467E-965A-7EAACEFBC4AB -H "Authorization: Splunk B5A79AAD-D822-46CC-80D1-819F80D7BFB0" -d 'Hello World'
I guess the 'channel' is easily sent through BOOMR.init as a key value pair but setting the header "Authorization: Splunk B5A79AAD-D822-46CC-80D1-819F80D7BFB0" is what we are missing out of the box for now.

**Comment by bluesmoon** [comment]
yup, since this is only possible via XHR beacons, and those are not the default, it isn't part of the library, however we'd be willing to accept a patch.
