### ISSUE TITLE
beacon_type: "POST" does not seem to have an impact

### ISSUE THREAD

**Issue by tmartin14** [SOASTA/boomerang#111]
I'm attempting to use boomerang.js, but would like to use the POST method rather than a GET (with all parameters on the URL).    I added a setting of  [beacon_type: "POST"] to my BOOMR.init(), but that does not seem to have an impact.   

Is this a known bug or expected behavior?

**Comment by andreas-marschke** [comment]
Have a look at the `real_sendBeacon()` function in boomerang.js. By default Boomerang will by itself decide when to use POST or GET depending on the size of the beacon data payload we are trying to transfer. That means a beacon including resource-timing (found in the restiming.js plugin) will result in a beacon that has a too long URL to work safely via GET , so at that point we are  using POST instead. 

`beacon_type` will do nothing technically at that point unless you are actively checking for that flag in your `real_sendBeacon` function.

**Comment by tmartin14** [comment]
Thanks for the quick reply.    I tweaked my local version in the real_sendBeacon and was able to get my POST successfully.    I'll make the appropriate changes and submit them in a bit so that others can use POST explicitly and add an Authorization token if needed.

**Comment by tmartin14** [comment]
I've made the required changes, but apparently do not have the appropriate permissions to commit them.   Can someone help with this?

**Comment by bluesmoon** [comment]
@tmartin14 submit a pull request from your own clone.  Even core developers have to do it that way.

**Comment by tmartin14** [comment]
Thanks @bluesmoon , I cloned SOASTA/boomerang locally, created a new branch (post-and-auth-support) and made my changes locally.   When I try to 'publish' or create a 'Pull Request' I get an error saying I am not authorized.    

I'm sure I'm missing something, but any help would be greatly appreciated.

**Comment by bluesmoon** [comment]
You need to create a fork under your own github account, then set it as a
remote and push your changes to it. After this, submit a pull request from
the github UI from your own account's fork.
