### ISSUE TITLE
detect browser close

### ISSUE THREAD

**Issue by mohanvasam** [SOASTA/boomerang#113]
Hi All,

I am new to JS and Boomerang. I am using boomerang in my project, I want to track if the user closes the browser when page not loaded fully -because of the slow internet or for any other issues.

can i do this using boomerang? How?

Thanks,
Mohan Vasam

**Comment by bluesmoon** [comment]
There's only a 40% chance of success, but boomerang will send a not loaded
beacon if the user leaves a page before it completes loading. You can
detect this by looking for the `rt.abld` flag on the beacon. This flag will
not have any value. You need to check for its existence.

Also note that it is possible that the user left the page by clicking a
link before the page loaded. You should check if the `nu` parameter is set
to URL do detect this.

If abld is set but nu is not set, then the user closed your site.

**Comment by mohanvasam** [comment]
Thanks for the help!
