### ISSUE TITLE
addVar on page unload

### ISSUE THREAD

**Issue by mohanvasam** [SOASTA/boomerang#114]
Hi All,

I am new to Boomerang, trying to addVar when the user closes the browser/window. Below is my code which is not working. It is working when i place 'BOOMR.addVar('t_abandon' , 'yes' );' outside the onbeforeunload.

`<script src="/js/boomerang-minify.js"></script>
<script>
  BOOMR.init({
     beacon_url: 'https://www.mysite.com',
  });
 window.onbeforeunload = function() {
               BOOMR.addVar('t_abandon' , 'yes' );
        }
</script>
`

Thanks,
Mohan Vasam

**Comment by andreas-marschke** [comment]
Hey Mohan!

You can use our own internal event-handling to make sure this happens before a beacon is sent `onunload`:

```
BOOMR.subscribe("page_unload", function() {
  BOOMR.addVar("my-specia-var", 1);
});
```

Another option would be to have a look at our onload beacon as `plugins/rt.js` already sets the variable  `rt.quit` on unload beacons. There are more interesting beacon flags for different unload types `rt.js` can set for you. Have a look at the code if you want. 

Cheers,

Andreas.

**Comment by mohanvasam** [comment]
Thanks, Andreas.
