### ISSUE TITLE
Error plugin with monitorEvents=true breaks websites

### ISSUE THREAD

**Issue by bripkens** [SOASTA/boomerang#116]
When the error plugin is used with the `monitorEvents` feature activated, it will break websites. This happens because the error plugin wraps the user provided listener in a function that catches all errors:

```javascript
if (impl.monitorEvents && BOOMR.window.addEventListener && BOOMR.window.Element) {
  impl.wrapFn("addEventListener", BOOMR.window, false, 1, E.VIA_EVENTHANDLER);
  impl.wrapFn("addEventListener", BOOMR.window.Element.prototype, true, 1, E.VIA_EVENTHANDLER);
  impl.wrapFn("addEventListener", BOOMR.window.XMLHttpRequest.prototype, true, 1, E.VIA_EVENTHANDLER);
}
```

Unfortuantely, any removal of listeners will now be impossible because the actual DOM API only knows about boomerang's wrapped error handler and not about the user's listener function.

**Comment by andreas-marschke** [comment]
Hey Ben!

We know about this short coming and have a set of changes supporting this in our commercial version. We will supply it at some point to the open source version.

Kind regards,

Andreas.

**Comment by bluesmoon** [comment]
@nicjansma don't we already have a fix for this?

**Comment by andreas-marschke** [comment]
@bluesnoon we do but we haven't merged it back to the open source branch
yet.

Am 01.12.2016 14:22 schrieb "Philip Tellis" <notifications@github.com>:

**Comment by orangecoding** [comment]
If this is a bug that could potentially break pages, why didn't you merge this back?

**Comment by bluesmoon** [comment]
@orangecoding unfortunately it's not simple because of a bunch of breaking changes in our in-house version, so it comes down to cherry-picking individual commits, which we've been slack on. Essentially we end up batching merges every month or two. Will try and get this in soon.

**Comment by nicjansma** [comment]
@orangecoding Sorry for the troubles. I'll backport this specific fix today.

**Comment by nicjansma** [comment]
Bug fixes:
https://github.com/SOASTA/boomerang/commit/1f8cadd129cdcd058db06374feb20f8bc6c84eef
https://github.com/SOASTA/boomerang/commit/b52f5b639d88af9a9069f4e130d26c34cfb91368
https://github.com/SOASTA/boomerang/commit/ef88f7cfdc9461a641521f658b40d5f11753effe

**Comment by bripkens** [comment]
Thank you!
