### ISSUE TITLE
Boomerang.js breaks the original web application

### ISSUE THREAD

**Issue by kelvinywkk** [SOASTA/boomerang#119]
Hi all,

I have been trying to apply boomerang to Microsoft Dynamics CRM. Basically I just quickly defined the client side script:

<script src="boomerang.js" type="text/javascript"></script>

after that the Dynamics CRM web application generated a lot of Undefined errors from the MS Dynamics CRM and the Web pages are not showing up. However I did debug the boomerang.js which does not report any error.  I am not sure what information I can further provide but could you please give me some idea how to proceed? Thanks.

Kelvin

**Comment by nicjansma** [comment]
@kelvinywkk Can you share some of the errors you're seeing?

If you remove `boomerang.js` from the page, do the errors go away immediately?

**Comment by nicjansma** [comment]
@kelvinywkk Any details?
