### ISSUE TITLE
Tracking "blocking time"

### ISSUE THREAD

**Issue by Aardvark71** [SOASTA/boomerang#121]
We have recently implemented a basic boomerang implementation (only rt plugin included) and noted that _our production website experiences issues with "blocking time"_
(as seen in chrome devtools... this "blocking time" is "the time the request spent waiting for an already established connection to become available").

This "blocking time" is not recorded by our boomerang implementation (I mean, all measurements seem to start from the start of the network request only).

Is there any means that we can measure this "blocking time"?

**Comment by nicjansma** [comment]
Hi @Aardvark71, are you talking about timings for the root page (e.g. NavigationTiming), or for resources on the page (ResourceTiming)?

The `rt` plugin only reports on time for the root page, which I wouldn't expect to be blocking waiting on a connection (as navigations generally trump all other fetches).

If you enable the `restiming` and `navtiming` plugins, you'll get the a Waterfall of resources (`restiming=`) and timings from NavigationTiming (`nt_*=`).  Based on the timestamps captured in either, you could calculate Blocking Time (see _Blocking Time_ in http://nicj.net/resourcetiming-in-practice/ for how we do it)

**Comment by nicjansma** [comment]
Please let us know if this is still an issue.

**Comment by Aardvark71** [comment]
Way too late for this, but still wanted you to know: BIG THANKS for your answer !

Especially the link to your blog article explaining it all in depth was a big help.
