### ISSUE TITLE
No boomerang version

### ISSUE THREAD

**Issue by ruslanmogilevskiy** [SOASTA/boomerang#122]
boomerang.js has this line:
`BOOMR.version = "%boomerang_version%";`

and it is not replaced by a real version value further so the %boomerang_version% text is sent to the backend.

**Comment by andreas-marschke** [comment]
Have you tried building a boomerang version using Grunt?

**Comment by ruslanmogilevskiy** [comment]
No, I haven`t. In some issue here I`ve read that getting sources and doing 'npm i' is enough to build boomerang. As far as I know, grunt is needed to bundle Boom and required plugins together but if I don`t need this (I don`t have it installed and dont`t want to) why not just set the version in sources to use Boom either via npm or grunt?

**Comment by nicjansma** [comment]
Hi @ruslanmogilevskiy 

As the [documentation states](https://github.com/SOASTA/boomerang#2-build-boomerang), you will need to use `grunt` to build Boomerang and the plugins.  This will set `%boomerang_version%`.

**Comment by ruslanmogilevskiy** [comment]
@nicjansma, seems grunt script only injects this single variable (boomerang_version) and bundle plugins. Why not include the version value into the boomerang.js to not force others to use grunt whose bundle plugins manually?

**Comment by bluesmoon** [comment]
@ruslanmogilevskiy that would require us to manually update boomerang.js only to change the version number which is automatically generated.
