### ISSUE TITLE
Limit variable lifetime by current beacon only

### ISSUE THREAD

**Issue by ruslanmogilevskiy** [SOASTA/boomerang#123]
If add a variable via BOOMR.addVar it will be sent in all further beacons that is not good in some cases.
Via variables, I`m trying to tag beacons that contain different timers data to parse them appropriately on backend. 
So my question is how to limit the variable lifetime by only the coming to send/current beacon or remove them right after the bacon was sent (there is no afterBeacon event)?

**Comment by andreas-marschke** [comment]
You can subscribe to `onbeacon` and remove the var that you are interested in not retaining at that point. Have  a look at the `real_sendBeacon` method in `boomerang.js` for more information.

**Comment by ruslanmogilevskiy** [comment]
`onbeacon `event doesn't work properly (seems it is a bug) because Boom firstly prepare the request (POST in my case) content in `paramsJoined` JS variable and then clones all registered variables from `impl.vars` to `varsSent` and passes `varsSent` into `onbeacon `handlers. 
Three problems here:
1) even if you delete a variable in an `onbeacon `handler it only being removed from that `varsSent `temp array and this array goes nowhere (not used for the request). Bug?
2) even if you would be able to remove a variable from a real list of registered variables (`impl.vars`) these changes won't affect the request because list of variables are concatenated earlier into `paramsJoined`  variable.
3) it would be good to have an afterbeacon event to be able to remove unneeded variables after beaconing. Or, add lifetime to each variable with constants like `OneTime `(used for one nearest beacon and auto-deleted by Boom)

**Comment by andreas-marschke** [comment]
Ah my bad. I missed out that you were supposed to call `removeVar`. 
ie.:
```
BOOMR.subscribe("onbeacon", function() { 
  ["var1", "var2"].forEach(function(v) {
    BOOMR.removeVar(v); 
  });
});
```

This way when the beacon is sent out the var is not in BOOMRs `impl.vars` anymore and you can add new ones at that point.

**Comment by ruslanmogilevskiy** [comment]
Thanks, I already used this hack. 
It is a hack for me because Boom passes a copied array of variables (varSent) into this handler but doesn't use this array in real_sendBeacon anywhere and changes in this array doesn't affect anything.

**Comment by nicjansma** [comment]
@ruslanmogilevskiy The method @andreas-marschke mentions is the correct way to remove variables that should live for a single beacon.  This is how all of the plugins handle the same situation.

We purposely send a copy of the current beacon values (`varsSent`) to all listeners of the `onbeacon` event, so every plugin can get a full picture of every variable sent on that beacon.  If we sent the original array (`impl.vars`), and plugin A calls `BOOMR.removeVar("a")`, plugin B would not see that the variable `"a"` was sent on the beacon.

Using `BOOMR.removeVar("x")` in the `onbeacon` callback is the recommended way of removing variables.

There are currently two events during beaconing, `before_beacon` and `onbeacon`:

* `before_beacon` is called prior to building the Beacon URL, so if there are any last-minute variables that need to be added, you can do it there.

* `onbeacon` is at the point we've decided the final beacon URL, and can be used as cleanup for any variables put on the beacon (anything done during `onbeacon` won't affect the current beacon).  This is what you're asking for with `afterbeacon`.
