### ISSUE TITLE
Auth token is added to beacon even if not specified

### ISSUE THREAD

**Issue by ruslanmogilevskiy** [SOASTA/boomerang#124]
The real_sendBeacon method contains following code when POST method is used:

if (typeof impl.beacon_auth_token !== "undefined") {
   if (typeof impl.beacon_auth_key === "undefined") {
        impl.beacon_auth_key = "Authorization";
}
xhr.setRequestHeader(impl.beacon_auth_key, impl.beacon_auth_token);
}

The problem is that beacon_auth_token is '' (empty string) by default and even if I don`t want authorization to happen on backend the Authorization XHR header is added because first IF is passed above.

**Comment by nicjansma** [comment]
Great catch!  Fixed via https://github.com/SOASTA/boomerang/commit/ae7c951c01dd35a746bc30c1ece9b925a09a8883
