### ISSUE TITLE
Boomerang support for angularjs SPAs

### ISSUE THREAD

**Issue by sivapavi** [SOASTA/boomerang#127]
I am trying to use boomerangJS for SPA built using AngularJS.
I have used following plugins/**boomerang.js,rt.js ,navtiming.js** in my main page .My main page created in angularjs .Remaining pages are built in non anugularjs . 

In angulrjs page i ve added the below mentioned boomerang configs.

1.
```html
<script> 
BOOMR.init({
          beacon_url: "https://mypage.io/beacon"
         });
        
window.BOOMR_config = {
    autorun: false,
    Angular: {
        enabled: true
    }
};

</script> 
```

2.
```html
<script>
angular.module("scotchApp")
    .run(["$rootScope", function($rootScope) {
        var hadRouteChange = false;

        $rootScope.$on("$routeChangeStart", function() {
            hadRouteChange = true;
        });
        // The following listener is required if you're using ui-router
        $rootScope.$on("$stateChangeStart", function() {
            hadRouteChange = true;
        });

        function hookAngularBoomerang() {
            if (window.BOOMR && BOOMR.version) {
                if (BOOMR.plugins && BOOMR.plugins.Angular) {
                    BOOMR.plugins.Angular.hook($rootScope, hadRouteChange);
                }
                return true;
            }
        }

        if (!hookAngularBoomerang()) {
            if (document.addEventListener) {
                document.addEventListener("onBoomerangLoaded", hookAngularBoomerang);
            } else if (document.attachEvent) {
                document.attachEvent("onpropertychange", function(e) {
                    e = e || window.event;
                    if (e && e.propertyName === "onBoomerangLoaded") {
                        hookAngularBoomerang();
                    }
                });
            }
        }
    }])
  
</script>
```

3.
```html
<script>
  (function(){
    if (window.BOOMR && window.BOOMR.version) { return; }
    var dom,doc,where,iframe = document.createElement('iframe');
    iframe.src = "javascript:false";
    (iframe.frameElement || iframe).style.cssText = 
    "width: 0; height: 0; border: 0; display: none;";
    where = document.getElementsByTagName('script')[0];
    where.parentNode.insertBefore(iframe, where);

    try {
        doc = iframe.contentWindow.document;
    } catch(e) {
        dom = document.domain;
        iframe.src="javascript:var d=document.open();d.domain='"+dom+"';void(0);"
        doc = iframe.contentWindow.document;
    }
    doc.open()._l = function() {
        var js = this.createElement("script");
        if(dom) this.domain = dom;
        js.id = "boomr-if-as";
        js.src = '//c.go-mpulse.net/boomerang/API_KEY';
        BOOMR_lstart=new Date().getTime();
        this.body.appendChild(js);
    };
    doc.write('<body onLoad="document._l();">');
    doc.close();
})();
</script>
```
when first time page is loaded it triggered the beacon request.But when i do the SPA subsequent navigations I don't see any new beacons getting triggered. Now want to know abt the below things 

1.Which function triggers a new beacon, after route change?
2.Will boomerang trigger new beacons each time a new view is displayed on page ?
3.Am I missing any configuration or code, to get it working ?
4.Or whether i need to add abv mentioned steps in my non angular js page ?

Could please kindly help me to resolve this issue ...

Thanks
Siva

**Comment by andreas-marschke** [comment]
Hey Siva!

Seeing as you are using the Boomerang Snippet for SOASTA, you will likely not need to build Boomerang yourself as it is already using  a pre-built Boomerang version that should work for your requirements. If you use mPulse please don't call `BOOMR.init()` unless you know exactly what you are doing or have been instructed so as `BOOMR.init` does more than just setting up/initializing Boomerang with a new configuration. Overriding the beacon_url like this will also prevent your config from working with mPulse as beacons will not end up on our collectors.

Keep in mind when you build your own Boomerang and deploy it to your page, you will need all of these Plugins to get a basic working boomerang up and running:
 - `plugins/spa.js`: our Core SPA handling plugin that is used by most/all our SPA-specific plugins
 - `plugins/angular.js`: code to integrate properly with Angular such as hooking into your rootScopes navigation events
 - `plugins/auto-xhr.js`: To track XHRs that are triggered by your SPAs navigation event as well as MutationObserver events watching until the page has settled again.

Now to your questions:
> Which function triggers a new beacon, after route change?
There are many places in our code that can individually trigger a new beacon, but they all will go back to `BOOMR.sendBeacon` to queue up a new beacon to be sent and `BOOMR.real_sendBeacon` which is called asynchronously and handles the actual sending of the Beacon. Have a look around our integration between `plugins/auto-xhr.js` and `plugins/spa.js` to understand how we handle navigations. Essentially the beacon is triggered by AutoXHR once we realize that the page has 'settled'. Checkout the _Performance Beacon_ post @nicjansma wrote on how SPA is handled by us.

> Will boomerang trigger new beacons each time a new view is displayed on page ?
If we detect a navigation being started (see the places in `plugins/angular.js` that we instrument/listen to for this) we will send a beacon once the navigation has ended.

> Am I missing any configuration or code, to get it working ?
As mentioned in the opening paragraph you are using `BOOMR.init` which should not be necessary as it is already called when we retrieve `config.js` in mPulse Boomerang

Lastly, should you be an mPulse user, feel free to reach out to our support staff there instead of asking here on our open source repository. They are able to give you tailored support for you based on your configuration in mPulse. This repository is only for people using Boomerang outside the context of mPulse.

Cheers,

Andreas

**Comment by sivapavi** [comment]
Thanks   @andreas-marschke Andreas!
Am not a user of mplus , Have followed the steps which you have mentioned above(Included spa.js,angular.js,auto-xhr.js) .But still am facing the issue for getting beacon request . please find the attached screen shot .

![error](https://cloud.githubusercontent.com/assets/26815667/24598027/f4763e1c-1866-11e7-9889-ba3145e95776.PNG)

Could you please help me to fix this ..


Thanks
Siva.P

**Comment by andreas-marschke** [comment]
Hey @sivapavi !

Thanks for your response. Looking at the `spa.js` code I realized that you will also require the RoundTrip plugin (`plugins/rt.js`). I apologize.

Also keep in mind that you can build your own version of boomerang using Grunt. The plugins you include are defined in plugins.json. Should you not require a plugin you can remove it. But you should be aware which plugins depend on which.

Cheers,

Andreas.

**Comment by sivapavi** [comment]
Hai @andreas-marschke   @nicjansma 
Thanks for your valuable response!

Am using the below mentioned js's in my SPA page .

<script src="boomerang.js" type="text/javascript"></script>
 <script src="navtiming.js" type="text/javascript"></script>
   <script src="bw.js" type="text/javascript"></script>
  <script src="spa.js" type="text/javascript"></script>
  <script src="rt.js" type="text/javascript"></script>
  <script src="angular.js" type="text/javascript"></script>
  <script src="js/auto-xhr.js" type="text/javascript"></script>
And also updated the Boomr.init() method .
BOOMR.init({
        Angular: {
              enabled: true
        }
        autorun: false,
        instrument_xhr: false	
        });
Still am facing the issue for genrating beacon request for every sub navigations of my SPA .
Am very new to this , please kindly correct me if am doing anything wrong !

Thanks
Siva

**Comment by nicjansma** [comment]
@sivapavi Can you confirm that you are _not_ using the mPulse loader snippet (item 3 in your original post)?  If you include the mPulse loader snippet as well it could break things if you're trying to use the open-source version.

Can you share a demo page with the issues?

In your above code, you're linking to `js/auto-xhr.js`, while all of the other plugins are just in the root directory.  Is that correct?

**Comment by sivapavi** [comment]
Thanks for your repsonse @nicjansma !

1.Can you confirm that you are not using the mPulse loader snippet (item 3 in your original post)? 
     _Am not using the mPluse loader code in my demo page ._

2.Can you share a demo page with the issues?
     _yeah sure , please find the below screen shot of demo page and error ._

![error](https://cloud.githubusercontent.com/assets/26815667/24641675/1b1fb544-191f-11e7-8061-eb46cbe59732.JPG)
Also i have included my sample demo code here . please review 
-------------------------------------------------------------------------------------------------
index.html
<!DOCTYPE html>

<html ng-app="scotchApp">

<head>
  
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" />
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" />

  
  <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.25/angular.min.js"></script>
  <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.25/angular-route.js"></script>
  <script src="script.js"></script>
</head>


<body ng-controller="mainController">

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Angular Routing Example</a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><i class="fa fa-home"></i> Home</a></li>
        <li><a href="#about"><i class="fa fa-shield"></i> About</a></li>
        <li><a href="#contact"><i class="fa fa-comment"></i> Contact</a></li>
      </ul>
    </div>
  </nav>

  <div id="main">
  
    
		
    <div ng-view></div>
    
  </div>
  
  <footer class="text-center" id="results">
    <p>View the tutorial on <a href="http://scotch.io/tutorials/javascript/single-page-apps-with-angularjs-routing-and-templating">Scotch.io</a></p>
  
    <p>View a tutorial on <a href="http://scotch.io/tutorials/javascript/animating-angularjs-apps-ngview">Animating Your Angular Single Page App</a></p>
  </footer>
  <script src="boomerang.js" type="text/javascript"></script>
  <script src="navtiming.js" type="text/javascript"></script>
  <script src="bw.js" type="text/javascript"></script>
  <script src="spa.js" type="text/javascript"></script>
    <script src="rt.js" type="text/javascript"></script>
  <script src="angular.js" type="text/javascript"></script>
  <script src="auto-xhr.js" type="text/javascript"></script>
  
  
  <script type="text/javascript">
  // Since we don't set a beacon_url, we'll just subscribe to the before_beacon function
  // and print the results into the browser itself.
  BOOMR.subscribe('before_beacon', function(o) {
    var html = "", t_name, t_other, others = [];
    if(o.t_done) { html += "This page took " + o.t_done + " ms to load<br>"; }
    if(o.t_other) {
      t_other = o.t_other.replace(/\|/g, ' = ').split(',');
      html += "Other timers measured: <br>";
      for(var i=0; i<t_other.length; i++) {
        html += "&nbsp;&nbsp;&nbsp;" + t_other[i] + " ms<br>";
      }
    }
    if(o.bw) { html += "Your bandwidth to this server is " + parseInt(o.bw/1024) + "kbps (&#x00b1;" + parseInt(o.bw_err*100/o.bw) + "%)<br>"; }
    if(o.lat) { html += "Your latency to this server is " + parseInt(o.lat) + "&#x00b1;" + o.lat_err + "ms<br>"; }
    var r = document.getElementById('results');
    r.innerHTML = html;
    for(var k in o) {
      if(!k.match(/^(t_done|t_other|bw|lat|bw_err|lat_err|u|r2?)$/)) {
        others.push(k + " = " + o[k]);
      }
    }
    if(others.length) {
      r.innerHTML += "Other parameters:<br>";
      for(var i=0; i<others.length; i++) {
        var t = document.createTextNode(others[i]);
        r.innerHTML += "&nbsp;&nbsp;&nbsp;";
        r.appendChild(t);
        r.innerHTML += "<br>";
      
      }
    }
  });

  BOOMR.init({
            Angular: {
              enabled: true
        }
        autorun: false,
        instrument_xhr: false	
        });
 </script> 
</body>
</html>
----------------------------------------------------------------------------------------------
2.Sub pages  Contact.html 
<div class="contact  text-center">
	<h1>Contact Page</h1>
	
	<p>{{ message }}</p>
</div>
--------------------------------------------------------------------------------------------
3.script.js 
	var scotchApp = angular.module('scotchApp', ['ngRoute']);
angular.module("scotchApp")
    .run(["$rootScope", function($rootScope) {
        var hadRouteChange = false;

        $rootScope.$on("$routeChangeStart", function() {
            hadRouteChange = true;
        });
        // The following listener is required if you're using ui-router
        $rootScope.$on("$stateChangeStart", function() {
            hadRouteChange = true;
        });

        function hookAngularBoomerang() {
            if (window.BOOMR && BOOMR.version) {
                if (BOOMR.plugins && BOOMR.plugins.Angular) {
                    BOOMR.plugins.Angular.hook($rootScope, hadRouteChange);
                }
                return true;
            }
        }

        if (!hookAngularBoomerang()) {
            if (document.addEventListener) {
                document.addEventListener("onBoomerangLoaded", hookAngularBoomerang);
            } else if (document.attachEvent) {
                document.attachEvent("onpropertychange", function(e) {
                    e = e || window.event;
                    if (e && e.propertyName === "onBoomerangLoaded") {
                        hookAngularBoomerang();
                    }
                });
            }
        }
    }])
  	
// create the module and name it scotchApp


	// configure our routes
	scotchApp.config(function($routeProvider) {
		$routeProvider

			// route for the home page
			.when('/', {
				templateUrl : 'homepage.html',
				controller  : 'mainController'
			})

			// route for the about page
			.when('/about', {
				templateUrl : 'about.html',
				controller  : 'aboutController'
			})

			// route for the contact page
			.when('/contact', {
				templateUrl : 'contact.html',
				controller  : 'contactController'
			});
	});

	// create the controller and inject Angular's $scope
	scotchApp.controller('mainController', function($scope) {
		// create a message to display in our view
		$scope.message = 'Everyone come and see how good I look!';
	});

	scotchApp.controller('aboutController', function($scope) {
		$scope.message = 'Look! I am an about page.';
	});

	scotchApp.controller('contactController', function($scope) {
		$scope.message = 'Contact us! JK. This is just a demo.';
	});
	
-------------------------------------------------------------------------------	
	
In your above code, you're linking to js/auto-xhr.js, while all of the other plugins are just in the root directory. Is that correct?
   _Sorry i have wrongly mentioned . All the boomerang  related js's are in the root directory itself._


Regards,
Siva

**Comment by nicjansma** [comment]
As shown in the screenshot you shared, you have a `Uncaught SyntaxError` in your code.

Specifically, you're missing a comma `,` in the `BOOMR.init()` call

![image](https://cloud.githubusercontent.com/assets/1004649/24767081/ce3f005a-1acb-11e7-9773-a4ba0ed34c58.png)

Once that's fixed, Boomerang sends a beacon (note you'll need to specify `beacon_url` in the config).

```
BOOMR.init({
    Angular: {
      enabled: true
    },
    autorun: false,
    instrument_xhr: false,
    beacon_url: "http://foo.com/"
});
```
