### ISSUE TITLE
Errors not reported after page load

### ISSUE THREAD

**Issue by buddyackerman** [SOASTA/boomerang#129]
I don't get errors reported after the page is loaded.  If something on a page that throws an error there is no reporting until I transition from that page.  I'm using this in an AngularJS 1.x app and the beacon gets sent only when I transition to another route or away from the app altogether.  That's not what I understand that the behavior is supposed to be.  Here is my Boomerang config:

    {
                instrument_xhr: true,
                autorun: false,
                beacon_type: "POST",
                beacon_url: BOOMERANG_API,
                Errors: {
                    enabled: true,
                    sendAfterOnload: true,
                    monitorGlobal: true,
                    monitorNetwork: true,
                    monitorConsole: true,
                    monitorEvents: true,
                    monitorTimeout: true,
                    maxErrors: 100
                },
                Angular: {
                    enabled: true
                }
    }

Also, the error data getting sent back is not in JSON format.  I added a test message to one of my click event handlers that looks like this:

    $window.BOOMR.plugins.Errors.send('Test Error');

The resulting error data looks like this

    ~(~(d~'j127nthg~f~(~(c~38~f~'debounceUpdateSelectionCallback~l~22~w~'webpack*3a*2f*2f*2f.*2fsrc*2fapp*2ffeatures*2f-options*2foption*2foption-controller.js*3f)~(c~19~f~'invokeFunc~l~95~w~'webpack*3a*2f*2f*2f.*2f*7e*2flodash*2fdebounce.js*3f)~(c~14~f~'trailingEdge~l~142~w~'webpack*3a*2f*2f*2f.*2f*7e*2flodash*2fdebounce.js*3f)~(c~14~f~'timerExpired~l~130~w~'webpack*3a*2f*2f*2f.*2f*7e*2flodash*2fdebounce.js*3f)~(f~'eval~l~null~w~'webpack))~m~'Test*20Error))

This is supposed to be JSON (at least based on what getErrorsForUrl method does).

**Comment by bluesmoon** [comment]
I'll let someone else respond about the beacon not being sent between transitions, but regarding the data encoding, that's using https://github.com/Sage/jsurl

**Comment by buddyackerman** [comment]
@bluesmoon Thanks for you response.  I replaced the default formatter with JSON.stringify.  I woudl like to know what it's not sending errors until page transition.  I did but a breakpoint in the `addError` method and  the reason that it's not sending is that this `if (!b.isDuringLoad && b.sendIntervalId === -1)` statement doesn't pass because `isDuringLoad` is true.  I'm not sure why it's true since the page is loaded and I'm just calling an action on my controller to post some data.

**Comment by buddyackerman** [comment]
@bluesmoon Thank you, that was the issue.

**Comment by nicjansma** [comment]
@buddyackerman If you have Angular support enabled `Angular: { enabled: true }`, you should have `autorun: false` as well, otherwise, you will be tracking the "traditional" page load time metric (to `onload`) instead of the SPA Hard Navigation page load time (which waits for resources fetched by angular.js).

If you weren't getting beacons with the config in your first post, did you have the correct Angular snippet "hooked" into your main Angular app?  Our documentation isn't the best here (we're working on it!), but you'll need a snippet like this one: http://docs.soasta.com/boomerang/#angularjs

**Comment by buddyackerman** [comment]
@nicjansma Yes, I added the hook.  I do get the errors without transitioning to a new page (unless they're duplicated) with `autorun: true`.
