### ISSUE TITLE
Adding global data

### ISSUE THREAD

**Issue by Kikketer** [SOASTA/boomerang#130]
I'm designated as a provider of Boomerang to help other applications within my organization track client analytics.  Anyway I'm trying to give each customer a custom JS file that has the startups and things they need so there's less thought and errors on their side getting things set up.

One of the things I need is to be able to distinguish which application is sending me the data.  Right now I was able to hijack the `properties` array in boomerang.js to add a universal "data" attribute.  That data attribute is then set in the init.

However I noticed other plugins don't use the same event scheme that boomerang base does.  Clicks for example, has it's own way of sending events and doesn't seem to have access to the `impl` of boomerang.  Thus I had to modify that plugin as well to add an additional bit of data for the added field (that's passed in the init).

Here's an example init:

```
BOOMR.init({
	data: {
		appname: '%appname%',
	},
	beacon_url: 'http://localhost:3000/beacon.gif',
	clicks: {
		click_url: 'http://localhost:3000/interaction.gif'
	}
})
```

The `'%appname%'` is populated by the grunt process.  Right now I mess with the clicks plugin as well to do something similar.

Is there an easy way to always pass a static bit of data regardless of the plugin or portion of this tool sending the data?

**Comment by bluesmoon** [comment]
Why not just use `addVar` after the `init` call? ie, something like this:
```javascript
BOOMR.init({
	beacon_url: 'http://localhost:3000/beacon.gif',
	clicks: {
		click_url: 'http://localhost:3000/interaction.gif'
	}
}).addVar("appname", "%appname%");
```

This will be sent on the beacon regardless of which plugin initiates the beacon.

**Comment by Kikketer** [comment]
That's what I was looking for.  Is there some docs that I had missed?

**Comment by bluesmoon** [comment]
It's documented here: https://soasta.github.io/boomerang/doc/api/BOOMR.html#methods

I don't understand what you mean by "doesn't work for the clicks plugin".  This adds a beacon parameter.  Maybe @andreas-marschke knows if the clicks plugin is doing anything special to send a beacon.

**Comment by Kikketer** [comment]
It seems the clicks plugin is doing it's own way of emitting the event.  I'm not sure what plugin development involves but I assume there's a way for a plugin to emit data using a standard way through boomerang.

https://github.com/SOASTA/boomerang/blob/master/plugins/clicks.js#L54

That's where it's sending it's data.  I've had to modify the send data object to include extras.

**Comment by bluesmoon** [comment]
yeah, it should typically just call `BOOMR.sendBeacon()` to send the beacon, but I think @andreas-marschke had other plans when he wrote the plugin, so we'll have to wait for him to chime in.

**Comment by andreas-marschke** [comment]
@kikketer yes the clicks plugin does it's own thing and is slated to be heavily revised or changed once I get time for it. If you intend to use click monitoring for performance monitoring purposes please use AutoXHR instead.

**Comment by Kikketer** [comment]
I was using it for more user interactions over performance.  It's fine the way it is now, was really just worried that I was going to have to modify more plugins.  But as far as I see it right now, things are running along fine with my modifications.

Don't feel pressured to "find time".  This will work.
Thanks @bluesmoon and @andreas-marschke
