### ISSUE TITLE
Help required for implementing Boomerang in React SPA !

### ISSUE THREAD

**Issue by sivapavi** [SOASTA/boomerang#131]
HI @nicjansma @andreas-marschke 

I have started implementing boomerang for React SPA. I have included boomerang,spa,history plugins in my main html page . Please find my sample html page here.

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>React Todos Example</title>
  
  <script src="plugins/boomerang.js" type="text/javascript"></script>

  <script src="plugins/navtiming.js" type="text/javascript"></script>
 
  <script src="plugins/rt.js" type="text/javascript"></script>

  <script src="plugins/restiming.js" type="text/javascript"></script>

  <script src="plugins/spa.js" type="text/javascript"></script>

  <script src="plugins/history.js" type="text/javascript"></script>

  <script src="plugins/auto-xhr.js" type="text/javascript"></script>
  </head>
  
<body>
  
<div id="root"></div>

<script type="text/javascript">
    BOOMR.init({
      autorun: false,
      History: {
        enabled: true,
  },
  beacon_url: "http://foo.com:8081/beacon"
 });

</script>
 </body>
</html>
```

Take look at the screenshot of my spa page .

![react1](https://cloud.githubusercontent.com/assets/26815667/24910691/2e5c8944-1ee6-11e7-8fde-bd4f1082e396.JPG)

My react page functions initiated  in  **_Bundle.js . In **_Bundle_.js i have included the  **_"BOOMR.plugins.History.hook()"_** Method

2. 
```
<script>
var history, hadRouteChange;
hadRouteChange = true;
  function hookHistoryBoomerang() {
    if (window.BOOMR && BOOMR.version) {
        if (BOOMR.plugins && BOOMR.plugins.History) {
            BOOMR.plugins.History.hook(history, hadRouteChange);
        }
        return true;
    }
}

if (!hookHistoryBoomerang()) {
    if (document.addEventListener) {
        document.addEventListener("onBoomerangLoaded", hookHistoryBoomerang);
    } else if (document.attachEvent) {
        document.attachEvent("onpropertychange", function(e) {
            e = e || window.event;
            if (e && e.propertyName === "onBoomerangLoaded") {
                hookHistoryBoomerang();
            }
        });
    }
}

</script>
```

But am getting the beacon request ,while the page loaded at 1st time . remaining activities are not generating beacon requests.

2. Please correct me if i missed-out anything 

Am very new to this , Could please help me to resolve this . 

Thanks
Siva.P

**Comment by nicjansma** [comment]
Hi @sivapavi for this issue and any future issues can you please put your full code / app on a server that we can reach to debug?

**Comment by sivapavi** [comment]
Hi @nicjansma 

Sure, I have attached the whole sample todos react-redux proj code here . please find the attachment.
Find the source code folder structure in below
My Main Entry Point js is : Index.js 

Action Creators : actions/index.js

Reducers : reducers/todos.js ,reducers/visibilityFilter.js,reducers/index.js

------------------------------------------------------------------------------------------------------
**_Presentational Components codes :_** 

Under Component folder : components/Todo.js 
 ,components/TodoList.js,components/Link.js,components/Footer.js,components/App.js
--------------------------------------------------------------------------------------------------------
Container Components (Needs To Connect the presentation component to **_Redux_**

containers/VisibleTodoList.js,containers/FilterLink.js,containers/AddTodo.js

------------------------------------------------------------------------------------------------------------
I have included the below mentioned  boomerang script in my main entry  **_index.js_** 

<script>
var history, hadRouteChange;
hadRouteChange = true;
  function hookHistoryBoomerang() {
    if (window.BOOMR && BOOMR.version) {
        if (BOOMR.plugins && BOOMR.plugins.History) {
            BOOMR.plugins.History.hook(history, hadRouteChange);
        }
        return true;
    }
}

if (!hookHistoryBoomerang()) {
    if (document.addEventListener) {
        document.addEventListener("onBoomerangLoaded", hookHistoryBoomerang);
    } else if (document.attachEvent) {
        document.attachEvent("onpropertychange", function(e) {
            e = e || window.event;
            if (e && e.propertyName === "onBoomerangLoaded") {
                hookHistoryBoomerang();
            }
        });
    }
}

</script>

The following Boomerang Plugins (boomerang.js,navtiming.js,rt.js,restiming.js,spa.js,history.js,auto-xhr.js) are added in my project.the plugins are available under the plugin folder.

1.Am I missing any configuration or code, to get it working ?
[todos.zip](https://github.com/SOASTA/boomerang/files/925529/todos.zip)


Could you please help to fix it assp.

Thanks
Siva.P

**Comment by nicjansma** [comment]
Hi @sivapavi, can you please put these files on an externally accessible webserver that we can just go directly to it?

**Comment by sivapavi** [comment]
HI @nicjansma 
Thanks for the reply ! 
I don't know the way of posting the files in that webserver . Could you please help me to achieve this .

**Comment by sivapavi** [comment]
HI @nicjansma 
I have tried to post my code but am getting the below access disabled message .
**_Uploads are disabled. File uploads require push access to this repository._**

**Comment by nicjansma** [comment]
What domain were you going to host this application on?  Or if you didn't have plans yet, any free webhosting service should do as it's just a HTML/JS app.

**Comment by sivapavi** [comment]
I don't have any plans ....Is there any free webhosting is available ? If its there i ill post my code as itis ..

**Comment by sivapavi** [comment]
Hi @nicjansma @bluesmoon @andreas-marschke 
please go through the below pasted sample react-redux codes and review the same . Bcz am not getting any options to post my code.


Main Entry Js : 


import React from 'react'
import { render } from 'react-dom'
import { createStore } from 'redux'
import { Provider } from 'react-redux'
import App from './components/App'
import reducer from './reducers'


import { createHistory } from 'history'; 

let history = createHistory();
//import createBrowserHistory from 'history/lib/createBrowserHistory';

var hadRouteChange = false;
//var history;
//var hookOptions = {};


**function hookHistoryBoomerang() {
    if (window.BOOMR && BOOMR.version) {
        if (BOOMR.plugins && BOOMR.plugins.History) {
            BOOMR.plugins.History.hook(history, hadRouteChange);
        }
        return true;
    }
}

if (!hookHistoryBoomerang()) {
    if (document.addEventListener) {
        document.addEventListener("onBoomerangLoaded", hookHistoryBoomerang);
    } else if (document.attachEvent) {
        document.attachEvent("onpropertychange", function(e) {
            e = e || window.event;
            if (e && e.propertyName === "onBoomerangLoaded") {
                hookHistoryBoomerang();
            }
        });
    }
}**

const store = createStore(reducer)

render(
  
  <Provider store={store}>
    <App />
    
  </Provider>,
  document.getElementById('root')
)

-------------------------------------------------------
Action : action/index.js 

let nextTodoId = 0
export const addTodo = (text) => ({
  type: 'ADD_TODO',
  id: nextTodoId++,
  text
})

export const setVisibilityFilter = (filter) => ({
  type: 'SET_VISIBILITY_FILTER',
  filter
})

export const toggleTodo = (id) => ({
  type: 'TOGGLE_TODO',
  id
})

-------------------------------------------------------------------
Reducers : reducers/todos.js 
const todo = (state, action) => {
  switch (action.type) {
    case 'ADD_TODO':
      return {
        id: action.id,
        text: action.text,
        completed: false
      }
    case 'TOGGLE_TODO':
      if (state.id !== action.id) {
        return state
      }

      return {
        ...state,
        completed: !state.completed
      }
    default:
      return state
  }
}

const todos = (state = [], action) => {
  switch (action.type) {
    case 'ADD_TODO':
      return [
        ...state,
        todo(undefined, action)
      ]
    case 'TOGGLE_TODO':
      return state.map(t =>
        todo(t, action)
      )
    default:
      return state
  }
}

export default todos
---------------------------------------------------------
reducers/visibilityFilter.js
const visibilityFilter = (state = 'SHOW_ALL', action) => {
  switch (action.type) {
    case 'SET_VISIBILITY_FILTER':
      return action.filter
    default:
      return state
  }
}

export default visibilityFilter
----------------------------------------------------------
reducers/index.js
import { combineReducers } from 'redux'
import todos from './todos'
import visibilityFilter from './visibilityFilter'

const todoApp = combineReducers({
  todos,
  visibilityFilter
})

export default todoApp
---------------------------------------------------------------------------
Presentational Components codes :

Under Component folder : components/Todo.js

import React, { PropTypes } from 'react'

const Todo = ({ onClick, completed, text }) => (
  <li
    onClick={onClick}
    style={{
      textDecoration: completed ? 'line-through' : 'none'
    }}
  >
    {text}
  </li>
)

Todo.propTypes = {
  onClick: PropTypes.func.isRequired,
  completed: PropTypes.bool.isRequired,
  text: PropTypes.string.isRequired
}

export default Todo
---------------------------------------------------------------------------
components/TodoList.js
import React, { PropTypes } from 'react'
import Todo from './Todo'

const TodoList = ({ todos, onTodoClick }) => (
  <ul>
    {todos.map(todo =>
      <Todo
        key={todo.id}
        {...todo}
        onClick={() => onTodoClick(todo.id)}
      />
    )}
  </ul>
)

TodoList.propTypes = {
  todos: PropTypes.arrayOf(PropTypes.shape({
    id: PropTypes.number.isRequired,
    completed: PropTypes.bool.isRequired,
    text: PropTypes.string.isRequired
  }).isRequired).isRequired,
  onTodoClick: PropTypes.func.isRequired
}

export default TodoList
--------------------------------------------------------------

components/Link.js:
import React, { PropTypes } from 'react'

const Link = ({ active, children, onClick }) => {
  if (active) {
    return <span>{children}</span>
  }

  return (
    <a href="#"
       onClick={e => {
         e.preventDefault()
         onClick()
       }}
    >
      {children}
    </a>
  )
}

Link.propTypes = {
  active: PropTypes.bool.isRequired,
  children: PropTypes.node.isRequired,
  onClick: PropTypes.func.isRequired
}

export default Link
-----------------------------------------------------------------------------------
components/Footer.js:
import React from 'react'
import FilterLink from '../containers/FilterLink'

const Footer = () => (
  <p>
    Show:
    {" "}
    <FilterLink filter="SHOW_ALL">
      All
    </FilterLink>
    {", "}
    <FilterLink filter="SHOW_ACTIVE">
      Active
    </FilterLink>
    {", "}
    <FilterLink filter="SHOW_COMPLETED">
      Completed
    </FilterLink>
  </p>
)

export default Footer
-------------------------------------------------------------------------
components/App.js
import React from 'react'
import Footer from './Footer'
import AddTodo from '../containers/AddTodo'
import VisibleTodoList from '../containers/VisibleTodoList'

const App = () => (
  <div>
    <AddTodo />
    <VisibleTodoList />
    <Footer />
  </div>
)

export default App
----------------------------------------------------------------------
Container Components (Needs To Connect the presentation component to Redux

containers/VisibleTodoList.js:

import { connect } from 'react-redux'
import { toggleTodo } from '../actions'
import TodoList from '../components/TodoList'

const getVisibleTodos = (todos, filter) => {
  switch (filter) {
    case 'SHOW_ALL':
      return todos
    case 'SHOW_COMPLETED':
      return todos.filter(t => t.completed)
    case 'SHOW_ACTIVE':
      return todos.filter(t => !t.completed)
    default:
      throw new Error('Unknown filter: ' + filter)
  }
}

const mapStateToProps = (state) => ({
  todos: getVisibleTodos(state.todos, state.visibilityFilter)
})

const mapDispatchToProps = {
  onTodoClick: toggleTodo
}

const VisibleTodoList = connect(
  mapStateToProps,
  mapDispatchToProps
)(TodoList)

export default VisibleTodoList
-------------------------------------------------------------------------------------

containers/FilterLink.js:
import { connect } from 'react-redux'
import { setVisibilityFilter } from '../actions'
import Link from '../components/Link'

const mapStateToProps = (state, ownProps) => ({
  active: ownProps.filter === state.visibilityFilter
})

const mapDispatchToProps = (dispatch, ownProps) => ({
  onClick: () => {
    dispatch(setVisibilityFilter(ownProps.filter))
  }
})

const FilterLink = connect(
  mapStateToProps,
  mapDispatchToProps
)(Link)

export default FilterLink
--------------------------------------------------------------------------------
containers/AddTodo.js
import React from 'react'
import { connect } from 'react-redux'
import { addTodo } from '../actions'

let AddTodo = ({ dispatch }) => {
  let input

  return (
    <div>
      <form onSubmit={e => {
        e.preventDefault()
        if (!input.value.trim()) {
          return
        }
        dispatch(addTodo(input.value))
        input.value = ''
      }}>
        <input ref={node => {
          input = node
        }} />
        <button type="submit">
          Add Todo
        </button>
      </form>
    </div>
  )
}
AddTodo = connect()(AddTodo)

export default AddTodo
-----------------------------------------------------------------------------

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>React Todos Example</title>
  
  <script src="plugins/boomerang.js" type="text/javascript"></script>

  <script src="plugins/navtiming.js" type="text/javascript"></script>
 
  <script src="plugins/rt.js" type="text/javascript"></script>

  <script src="plugins/restiming.js" type="text/javascript"></script>

  <script src="plugins/spa.js" type="text/javascript"></script>

  <script src="plugins/history.js" type="text/javascript"></script>

  <script src="plugins/auto-xhr.js" type="text/javascript"></script>
  </head>
  
<body>
  
<div id="root"></div>

**<script type="text/javascript">
    BOOMR.init({
      autorun: false,
      History: {
        enabled: true,
  },
  beacon_url: "http://foo.com:8081/beacon"
 });

</script>**
 </body>
</html>


Please help me to fix this . If i ve missedout anything please kindly help .

Am I missing any configuration or code, to get it working ?
Whether i have included the boomerang  **"History.js"** plugins and methods correctly or not ?

Thanks
Siva.P

**Comment by nicjansma** [comment]
Hi @sivapavi we won't be able to help unless you can put all of this code live on a running website.
