### ISSUE TITLE
Boomerang record some abnormal timestamp of request timing

### ISSUE THREAD

**Issue by Tideorz** [SOASTA/boomerang#132]
i use boomerang help to get the page load time information,
but it's strange that sometimes, i'll get abnormal timestamp,
you can see as follow:
boomerang_nt_con_end	   	9,999,999,999,999
boomerang_nt_con_st	   	9,999,999,999,999
boomerang_nt_dns_end	   	9,999,999,999,999
boomerang_nt_dns_st	   	9,999,999,999,999
boomerang_nt_domcomp	   	9,999,999,999,999
boomerang_nt_domcontloaded_end	   	9,999,999,999,999
boomerang_nt_domcontloaded_st	   	9,999,999,999,999
boomerang_nt_domint	   	9,999,999,999,999
boomerang_nt_domloading	   	9,999,999,999,999
some request timing reach to 9,999,999,999,999, which must be wrong, Have anyone met it before ?

**Comment by bluesmoon** [comment]
This is a bot. We see it very often.

**Comment by Tideorz** [comment]
And i found another situation is that the number is not 9,999,999,999,999, but some random number which is lager than the max timestamp limitation (2^32-1), have you met it before ? 
such as number 2,982,456,573,769. Or they are just the same issues ?

**Comment by bluesmoon** [comment]
JavaScript dates/timestamps are not limited to 2^32-1.  They range from -100,000,000 days to +100,000,000 days relative to 1 Jan 1970.  However, any date in the future is also considered either a bot, a browser bug or someone with a misconfigured system clock and we ignore absolute times on beacons with these values.  We will still consider relative times if they fall within range, so you can look at `nt_load_end - nt_fet_st` to get the total load time of the page.

**Comment by Tideorz** [comment]
thanks :)
