### ISSUE TITLE
How to use BOOMR.plugins.History.hook() Boomerang function

### ISSUE THREAD

**Issue by sivapavi** [SOASTA/boomerang#135]
Hi Team,

In my react-redux spa source code **_where i need to include the below mentioned boomerang function_ ?**

1. <script>

var history, hadRouteChange;
history = createHashHistory();
function hookHistoryBoomerang() {
    if (window.BOOMR && BOOMR.version) {
        if (BOOMR.plugins && BOOMR.plugins.History) {
            BOOMR.plugins.History.hook(history, hadRouteChange);
        }
        return true;
    }
}

if (!hookHistoryBoomerang()) {
    if (document.addEventListener) {
        document.addEventListener("onBoomerangLoaded", hookHistoryBoomerang);
    } else if (document.attachEvent) {
        document.attachEvent("onpropertychange", function(e) {
            e = e || window.event;
            if (e && e.propertyName === "onBoomerangLoaded") {
                hookHistoryBoomerang();
            }
        });
    }
}
<script>

Please kindly help !

Thanks
Siva.P

**Comment by nicjansma** [comment]
Hi Siva,

It really depends on your app -- additional sample code can be found here: http://docs.soasta.com/boomerang/#react

**Comment by sivapavi** [comment]
@nicjansma 

Am trying to implement the boomerang for my sample TodoList react-redux code ,which is available in this location - http://redux.js.org/docs/basics/ExampleTodoList.html 

And i have included the additional code also in my main react Entry point **_(Index.js)_** ,which is present in the given  (http://docs.soasta.com/boomerang/#react)  link . But am getting below errors .

![react-redux error](https://cloud.githubusercontent.com/assets/26815667/25226200/af1e7a22-25e1-11e7-8738-dbe5a877014a.JPG)


Could you please help me .
Thanks
Siva.P

**Comment by andreas-marschke** [comment]
Looks like your build tool is complaining about the BOOMR token not being defined (`no-undef`). Since BOOMR comes from a different script and not from your code in that file. You'll need to flag it as being part of global scope.

**Comment by sivapavi** [comment]
@andreas-marschke 
I have defined my BOOMR token in globally. but now am getting below error. help me to fix this issue .
![error-token unexpected](https://cloud.githubusercontent.com/assets/26815667/25229797/437015f2-25ef-11e7-8de9-1279eb1d47e5.JPG)

Please take a look once in attached screenshot i ve added boomerang functions correctly in my main react-redux index.js.
![1234](https://cloud.githubusercontent.com/assets/26815667/25229890/b58d0ed8-25ef-11e7-873c-863b93b8eae4.png)

**Comment by andreas-marschke** [comment]
Please. Post a script instead of an image. it's hard to read and or comprehend the image.

**Comment by sivapavi** [comment]
@andreas-marschke  sure . Please find below

import React from 'react'
import { render } from 'react-dom'
import { createStore } from 'redux'
import { Provider } from 'react-redux'
import App from './components/App'
import reducer from './reducers'

import createHistory from 'history'

(function(){
  var history, hadRouteChange;
	if (BOOMR.plugins.History || typeof BOOMR.plugins.SPA === "undefined") {
		return;
	}
	
//register as a SPA plugin
BOOMR.plugins.SPA.register("History");

BOOMR.plugins.History = {
 
	  	function hookHistoryBoomerang() {
	  	  
		  if (window.BOOMR && BOOMR.version) {
        if (BOOMR.plugins && BOOMR.plugins.History) {
            BOOMR.plugins.History.hook(history, hadRouteChange);
        }
        return true;
    }
}

if (!hookHistoryBoomerang()) {
  
    if (document.addEventListener) {
      
        document.addEventListener("onBoomerangLoaded", hookHistoryBoomerang);
    } else if (document.attachEvent) {
        document.attachEvent("onpropertychange", function(e) {
            e = e || window.event;
            if (e && e.propertyName === "onBoomerangLoaded") {
                hookHistoryBoomerang();
            }
        });
    }
}

function onEnter() {
    hadRouteChange = true;
}

};

  
}());
    
    
//const history = createHistory()

const store = createStore(reducer)

render(
  <Provider store={store}>
  <Router history={history} onEnter={onEnter} />
    <App />
  </Provider>,
  
  document.getElementById('root')
)

**Comment by andreas-marschke** [comment]
@sivapavi Hey. Could you contact me on my mail address that is referenced on my Github account?

**Comment by sivapavi** [comment]
@andreas-marschke - I have sent a mail now .Please kindly check and help
