### ISSUE TITLE
How to get the corresponding url in  Boomcatch 

### ISSUE THREAD

**Issue by sivapavi** [SOASTA/boomerang#136]
HI @nicjansma @andreas-marschke 
Am trying to running the boomcatch in forevrer mode using below mentioned commands

sudo forever -sa \
  -l /var/log/boomcatch/boomcatch-forever.log \
  -o /var/log/boomcatch/boomcatch-access.log \
  -e /var/log/boomcatch/boomcatch-error.log \
  /home/ubuntu/.nvm/versions/node/v4.7.3/bin/boomcatch \
    --port 8888 \
    --host 127.0.0.1 \
     --fwdPort 8089 \
    > /dev/null 2>&1 &

I could see the boomcatch passing the below mentioned  values to  assigned 8089 port and am storing these valuse in my influxdb with the help of telegraf.

rt.load:633719|ms
navtiming.connect:101|ms
navtiming.response:3|ms
navtiming.dom:299|ms
navtiming.domContent:72|ms
navtiming.load:1|ms

But am not able to find the particular source url for the triggered outputs.

Is there any command available to send the url name along with the abv mentioned output in boomcatch .?

Please kindly help me !

Thanks
Siva.P

**Comment by nicjansma** [comment]
Hi @sivapavi, are you asking about the URL of the page sending the beacon?  That should be in the `u` beacon parameter.

**Comment by bluesmoon** [comment]
@sivapavi please ask on the boomcatch project.  That is not maintained by us.
