### ISSUE TITLE
unable to post the beacon results to boomcatch

### ISSUE THREAD

**Issue by sivapavi** [SOASTA/boomerang#140]
Hi @nicjansma @bluesmoon 

Suddenly Am not able to get the beacon results in boomcatch error like  **_"boomerang.js:1537 POST https://boomcatch-demo-indhusiva.c9users.io/beacon 503 (Service Unavailable)"_** .
But seems Boomcatch is running fine .and i have defined my beacon explicitly using BOOMR.init() method

 And i could see some error in boomerang.js please take a look in the below screenshot.
![isseu2](https://cloud.githubusercontent.com/assets/26815667/25989344/55318ec0-3719-11e7-99e5-8f0b6401d8d3.PNG)

And more clarification required . I could see the boomerang related pulgins are got updated in  10 days before.(https://github.com/SOASTA/boomerang/tree/master/plugins) .
So should i need to replace my pulgins with new one ?

Please kindly help !

Thanks
Siva.P

**Comment by andreas-marschke** [comment]
@sivapavi Your server returned a ' 503 (Service Unavailable)"' Since we don't support boomcatch we can't answer these questions. Please ask the boomcatch project for help.

**Comment by sivapavi** [comment]
@andreas-marschke 
Thanks for the reply !

Regarding the uapdated boomerang plugins ,shall i need to replace my pulgins with new one regularly ?
Am refering the following link https://github.com/SOASTA/boomerang/tree/master/plugins.

**Comment by andreas-marschke** [comment]
We leave this up to the user. Please refer to the Merge Request referenced in the commit that updated the source code 10 days ago:

  https://github.com/SOASTA/boomerang/pull/134

You will find a large list of new features and bug fixes we added in that merge request.

**Comment by sivapavi** [comment]
Thanks @andreas-marschke

**Comment by andreas-marschke** [comment]
Closing issue
