### ISSUE TITLE
Recalculations of bandwidth and latency.

### ISSUE THREAD

**Issue by CryptoLocker** [SOASTA/boomerang#142]
Hi,
I have a page, wherein i added a button. Now could u please help me in writing an event listener, which is on click for the button. The button on-click should calculate the bandwidth and latency every time user click it and after that i am calling the sendBeacon(), so that i am listening to before_beacon method to capture the data. 
Thanks

**Comment by andreas-marschke** [comment]
Hey @CryptoLocker , 

a click event alone does not mean a network request has been sent. If you wish to test/measure the bandwidth your client has available to it, you can use the `bw.js` plugin in your Boomerang build.

Have a look at the [documentation for the BW plugin for some more info on it] (https://soasta.github.io/boomerang/doc/api/BW.html).

Cheers,

Andreas.

**Comment by CryptoLocker** [comment]
Hi @andreas-marschke ,

Thanks for the reply. Agreed to that. But i am using it something in this way..

this.buttonXYZ.on('click', function(o) {
                var boomrConfig = {
                    beacon_url: constants.routes.SAVE_REQUEST(),
                    autorun: false,
                    beacon_type: 'GET',
                    BW: {
                        base_url: constants.routes.BW_IMAGES(),
                        test_https: true,
                        block_beacon: true,
                        cookie_exp: constants.cookieExpirationSecs,
                        nruns: constants.numberOfIterationsForBandwidthCalcs
                    }
                };
                window.BOOMR.init(boomrConfig);
                window.BOOMR.page_ready();
                window.BOOMR.sendBeacon();
            });

And i have an event listener for before_beacon event to capture the data. But I noticed that the calculations are not happening except for the first time.

So is there something wrong in the way i have configured or calling it ?

Thanks

**Comment by bluesmoon** [comment]
@CryptoLocker when pasting code in your comments, please enclose it in the appropriate code fence so that it's easier to read.

The bandwidth test results will be saved in a cookie and will be reused from the cookie on subsequent calls.

Also, you should not be calling `sendBeacon` directly.

**Comment by CryptoLocker** [comment]
@bluesmoon Sure, thanks. Will definitely do that from next time whenever I insert any code.

We have configured that cookie expires after 3 minutes right..after that as well there are no recalculations happening even if I manually trigger the bandwidth cal function. 
And is there any better way then if i don't call `sendBeacon` method  since i am listening to before_beacon event.

Thanks a lot for your replies and support.

**Comment by bluesmoon** [comment]
`sendBeacon` is called internally by the plugin which is why you don't have to call it.  Can you show us the server on which you're running the site?
