### ISSUE TITLE
Beacon firing again when target form/page takes long to load?

### ISSUE THREAD

**Issue by rolaso** [SOASTA/boomerang#143]
Hi guys,

We are seeing an odd behavior from the tag in cases where the target page/form takes a while to load. It looks as if the beacon fires again (without the nu parameter) before the actual page load.

So, before I go deeper on my investigation, I wanted to run this by you guys and see if this is "by design"? I can't find anything on the documentation regarding this topic.

Thank you,

R

**Comment by rolaso** [comment]
Looking through past issues, I see that it may be related to [issue #43](https://github.com/SOASTA/boomerang/issues/43) . I'll investigate and report back.

Thank you

**Comment by nicjansma** [comment]
@rolaso Let us know if that's the cause.  If not, can you share a repro URL we can go to?

**Comment by rolaso** [comment]
Hi Nic,

Yes, I can confirm the "double firings" records all have the "rt.quit" parameter on them. We are in the process of cleaning them up and ignoring them from now on.

Thank you,

**Comment by nicjansma** [comment]
Great!
