### ISSUE TITLE
Session related data not coming in boomerang beacon !

### ISSUE THREAD

**Issue by sivapavi** [SOASTA/boomerang#144]
Hai @nicjansma /Team,

Am trying to implementing the RUM with open source boomerang javascripts pulgins .and am able to get the results of rt.js,navtiming.js ,restiming.js in my beacon request . But i didn't get anything related to "session"perameter/results in beacon. 

Note : And based on the mpluse guildliness , If i use mpulse script with API key, am getting *"Sessions"* related results in my boomerang beacon . 

Using mpulse script & API key IS that only possible way to get a session releated data in boomerang beacon ? 

Pls kindly help me !  If it is also possible with open source boomerang jvascript plugins or Are we need to write any custome code .?

If am anything wrong pls correct me !.

Thanks
Siva.P

**Comment by bluesmoon** [comment]
Hi @sivapavi none of the mPulse documentation applies to the open source boomerang.  For the opensource version have a look at the `guid.js` plugin.

**Comment by sivapavi** [comment]
@bluesmoon ,
Thanks for the response!. 
I have used guid.js also in webpage .Ididn't get any session related info's .:(

**Comment by bluesmoon** [comment]
Not sure what other session information you're looking for.

**Comment by sivapavi** [comment]
Hi @bluesmoon 
Even am not get the basic session details like (session id,session start & end time ,viewed pages in session) also .

**Comment by bluesmoon** [comment]
@sivapavi this is not supported.  Did you see any documentation on the site that mentions these fields?
