### ISSUE TITLE
Getting bw:NaN & bw_err:NaN results

### ISSUE THREAD

**Issue by sivapavi** [SOASTA/boomerang#145]
Hi @bluesmoon @nicjansma /Team,

My traditional web application is host in my localhost server. For measuring the bandwidth & latency of the user's network connection to my server i have included bw.js along with boomerang.js .the downloaded images are placed under /boomerang-image folder .But am getting only latency result and bandwidth result is NaN. 

Pls find in below mentioned  Boom.init() method which am using !
BOOMR.init({

                beacon_url: "http://localhost:8082/beacon",
                auto_run: false,
                 BW: {

                        base_url: "../boomerang-images/",
                        cookie: "BA",
                        block_beacon: true
                    },
                RT: {
                        cookie: "RT",
                        cookie_exp: 120
                   }
 });

Result am getting 

> **bw:NaN
> bw_err:NaN
> lat:10
> lat_err:0.96
> bw_time:1497597904
> 
> > bw_debug:l==0**

Could you please forgive me if i might have missed out anything in my code .I'd like to hear from you guys about this issue .

Reference console and network tab result
![images](https://user-images.githubusercontent.com/26815667/27217811-118ec93a-5299-11e7-8648-07ee7bc6d503.jpg)

![imgae2](https://user-images.githubusercontent.com/26815667/27217817-1add0326-5299-11e7-97a3-cdc942543381.png)
![image3](https://user-images.githubusercontent.com/26815667/27217830-25b52a9e-5299-11e7-87b0-8104f6fbec55.png)

Thanks
Siva.P

**Comment by bluesmoon** [comment]
Yeah, this is possibly not going to work on localhost since the bw images are actually loading up faster than the latency image, which is because you really don't have any network constraints.

**Comment by andreas-marschke** [comment]
Closing, as this isn't a bug but rather a problem in your configuration as @bluesmoon pointed out.

Please use a domain instead of localhost when testing with the BW plugin.
