### ISSUE TITLE
Boomerang license disclaimer question

### ISSUE THREAD

**Issue by quintenp** [SOASTA/boomerang#146]
Good day,

I want to use boomerang in my project I just have a question around what is required license and disclaimer wise at the top of my minified boomerang script to be fully compliant.

At the moment I have the following

```
/*
 * Copyright (c) 2011, Yahoo! Inc.  All rights reserved.
 * Copyright (c) 2011-2012, Log-Normal, Inc.  All rights reserved.
 * Copyright (c) 2012-2016, SOASTA, Inc. All rights reserved.
 * Copyrights licensed under the BSD License. See the accompanying LICENSE.txt file for terms.
 */
/* JavaScript MD5 1.0.1 Copyright 2011, Sebastian Tschan. Licensed under the MIT license. */
/* Boomerang Version: 1.0.1496997604 */
```

**Comment by bluesmoon** [comment]
You're all good.  We'll be updating that section soon, but for the current code, you should be ok.

**Comment by quintenp** [comment]
@bluesmoon thanks
