### ISSUE TITLE
 t_page value is not accurate in SPA page

### ISSUE THREAD

**Issue by weliame** [SOASTA/boomerang#149]
Hi team, 
I tagged boomerang in my SPA project and it works.It's really a great tool! But there is something wrong with `t_page` time in my code. When I reload a page the value is accurate. When I click a link which will trigger route change, the `t_page` is not accurate. Following is from console output,
```
spa.missed:1
u:http://localhost:9010/components/spark-calendar/02_date_picker
v:0.9
vis.st:visible
ua.plt:MacIntel
ua.vnd:Google Inc.
nu:http://localhost:9010/components/spark-calendar/02_date_picker
rt.start:manual
rt.tstart:1501816088280
rt.bstart:1501816074769
rt.end:1501816088770
t_resp:90
**t_page:14197**
t_done:490
t_other:t_domloaded|-11508,boomerang|15006,boomr_fb|-13511
r:http://localhost:9010/components/spark-calendar/03_date_range
r2:
http.initiator:spa
```
You may see the `t_page` is really larger than `t_done` time. 
Following is my code,
```
<script src="/images/boomr/boomerang.js"></script>
<script src="/images/boomr/spa.js"></script>
<script src="/images/boomr/auto-xhr.js"></script>
<script src="/images/boomr/history.js"></script>
<script src="/images/boomr/errors.js"></script>
<script src="/images/boomr/rt.js"></script>
<script>
    BOOMR.init({
        beacon_url: "http://localhost:8888/beacon",
        instrument_xhr: false,
        BW: {
            base_url: "https://github.com/SOASTA/boomerang/raw/master/images/",
            test_https: true,
            block_beacon: true
        }
    });
</script>
```

```
function hookHistoryBoomerang() {
  if (window.BOOMR && BOOMR.version) { // eslint-disable-line no-undef
    if (BOOMR.plugins && BOOMR.plugins.History) { // eslint-disable-line no-undef
      BOOMR.plugins.History.hook(history, true); // eslint-disable-line no-undef
    }
    return true;
  }
}

if (!hookHistoryBoomerang()) {
    if (document.addEventListener) {
        document.addEventListener('onBoomerangLoaded', hookHistoryBoomerang);
    } else if (document.attachEvent) {
        document.attachEvent('onpropertychange', (e) => {
            let evt = e || window.event;
            if (evt && evt.propertyName === 'onBoomerangLoaded') {
                hookHistoryBoomerang();
            }
        });
    }
}
```
Expect your idea and your info will help me a lot. Thanks in advance.

**Comment by nicjansma** [comment]
Hi @weliame , it looks like `t_page` here is too high? `14197` vs `490` for `t_done`?

We have some bug fixes related to these calculations.  Are you using the very latest code?  If so, I'll see what other fixes we haven't backported to the OS branch yet.

**Comment by weliame** [comment]
@nicjansma, thanks for your quick response. Yes, I mean `t_page` is too high.  I suppose `t_done = t_resp + t_done`, right? I am using the  latest code.

**Comment by weliame** [comment]
Hi @nicjansma, is there any real example for React  SPA monitor I can follow?

**Comment by nicjansma** [comment]
@weliame Like a sample app?  We have a very simple one here:

http://dev.nicj.net/react/

And better general documentation here:

**Comment by satya-ip** [comment]
Hi @nicjansma, is there any plan for VueJs SPA monitor? Pl share a link if there are any samples.

**Comment by nicjansma** [comment]
@satya-ip At this point we're encouraging everyone to use the History plugin with `auto:true`, which supports instrumentation of the `window.history` object and should track all user navigations that change the URL.

**Comment by nicjansma** [comment]
@weliame We've posted our most recent updates that have several bug fixes for SPA calculations in https://github.com/SOASTA/boomerang/pull/188.  Please review and open a new Issue if you're still having problems!
