### ISSUE TITLE
XHR_STATUS_ERROR Need help understanding use case

### ISSUE THREAD

**Issue by quintenp** [SOASTA/boomerang#150]
Hi guys,

Quick question I am seeing a lot of XHR_STATUS_ERROR  from the auto-xhr plugin coming from my app.  I am trying to triage/replicate these issues and In having a real hard'time with them I cant seem to replicate the problem nor does it seem to be impacting?

Could you possibly please explain a general scenario where this error would occur and if it has a high impact on my sites stability.

Thanks in advance!

**Comment by bluesmoon** [comment]
This is simply reporting that the XHR call threw a generic error event.  You can  subscribe to boomerang's `onxhrerror` event to get more details. Unfortunately there is no general scenario where this will occur. It will be unique to your site's design and the browser in use.

**Comment by quintenp** [comment]
@bluesmoon Thank you for the quick feedback! 

Would the server not return some status code in these scenarios something like a 500 with a message/stack trace or would I be able to pick that up on the event you recommended

**Comment by quintenp** [comment]
Also is there a easy way to trigger this error or is this to dynamic to replicate

**Comment by bluesmoon** [comment]
No, this error is for things that fail within the XMLHttpRequest object in the browser. It probably hasn't even sent a request to the server. If a request were sent and you got an error status, then we'd show you that status code. If a request were sent and we got no response, you'd get `XHR_STATUS_TIMEOUT`. If an error happened during open, you'd get `XHR_STATUS_OPEN_EXCEPTION` and if the request were aborted by your code, you'd get `XHR_STATUS_ABORT`.

If you're getting `XHR_STATUS_ERROR`, it means something went wrong in making the request and the browser didn't tell us any more than that.

**Comment by bluesmoon** [comment]
The best you could do is see which url caused it.

**Comment by quintenp** [comment]
That's exactly what I needed thanks! You have been a great help

**Comment by zhouyu94** [comment]
@bluesmoon I also encountered the same error, but did not find any problem with the requested url. so, Is there anything else that might cause this problem?  thanks!

**Comment by bluesmoon** [comment]
The cause would be different for every site. I cannot say anything without seeing the site in question.

**Comment by zhouyu94** [comment]
If it is you, what aspects will be checked?

**Comment by querymetrics** [comment]
@quintenp @zhouyu94 https://xhr.spec.whatwg.org/#event-xhr-error

It could happen for blocked cross-origin requests, requests blocked by CSP, dropped connections, blocked by an ad blocker, etc.

Test examples:
tests/page-templates/07-autoxhr/00-xhrs.html (For XHR API)
tests/page-templates/07-autoxhr/42-fetch-api.html (for Fetch API)

Or try this in the console with an ad blocker installed:
```
xhr = new XMLHttpRequest();
xhr.addEventListener("error", (event) => {console.log("XHR ERROR: " + JSON.stringify(event))});
xhr.open("GET", "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js");
xhr.send();
```
Boomerang will capture this as a XHR_STATUS_ERROR

**Comment by zhouyu94** [comment]
@querymetrics  Thanks! Maybe I found some other situations that caused me to have this problem.

I have two operating environments, they have same origin code.

env one: All correct, there is no abnormality.

env two: In this env, I found some code that I don’t know where to add to the html. this code include some js code. They are all confused.
		 some error like this: `Uncaught TypeError: Cannot read property 'round' of undefined at _$sn (eval at _$oH` and `Uncaught TypeError: _$je[_$bB[189]] is not a function at _$sn (eval at _$oH`.


i think, maybe the inexplicable code affect some error. so, i will check why these codes appear in my env two html.
		 
thanks again!

**Comment by querymetrics** [comment]
It also happens for requests with invalid/expired HTTPS certificates

**Comment by zhouyu94** [comment]
@querymetrics Thank you, I seem to find out why this problem occurs. Before the execution of my plug-in, some people have done some operations. These operations may affect the XmlHttpRequest in the window. After the boomerang plug-in is executed, it proxy XHR, causing the original method to be unusable.
And thanks again!
