### ISSUE TITLE
Integrating boomerang

### ISSUE THREAD

**Issue by mvraghunath** [SOASTA/boomerang#151]
Starting to integrate with boomerang for my project.. Could some one suggest any links

**Comment by nicjansma** [comment]
Hi @mvraghunath 

What kind of links are you referring to?

Documentation for the project is available in the README
https://github.com/SOASTA/boomerang

and
https://soasta.github.io/boomerang/doc/

**Comment by mvraghunath** [comment]
hey I looked at these links already. I want to know if you have any sample application that boomerang is integrated to so that I can take that as base

**Comment by nicjansma** [comment]
Libscore has a list of sites `BOOMR` is on: https://libscore.com/#BOOMR
