### ISSUE TITLE
Same use of Boomerang for different apps (by the way different tabs)

### ISSUE THREAD

**Issue by CapucinePr** [SOASTA/boomerang#152]
Hi everyone,
I would like to implement Boomerang to measure the time of each request (ajax or not) made by all the employees of my company, on all our apps, measuring the time spent between the moment the employee sends a request (by sending a form, clicking on a link,...) and the moment the response is received and the page is usable again. The goal is then to store each value of these measures in my database.
But in our apps, we can sometimes click on a link aiming to open another application, that opens a new tab with the target app.
Unfortunately, it seems like Boomerang can't measure the time spent from the moment the employee clicks on the link in App1, and the moment the App2 (which is open in another tab ) is usable..
Am I wrong ? How can I handle it ?

**Comment by andreas-marschke** [comment]
Hey @CapucinePr !

If App2 also has Boomerang in the page, you can measure when the app is usable with boomerang and use the onload event ie. `BOOMR.init({ autorun: true })`. However since Boomerang can't see what the entire browser is doing, only the current webpage/tab the click in App1 won't be part of what Boomerang can beacon on.

Does that help?

**Comment by CapucinePr** [comment]
Yes that helps, thank you ! 
Moreover, I'd like to regroup the resources for each request (you know, a request can send an xmlhttprequest, and then imply resources like img, css, etc), and measure the time elapsed for this bundle. For example, each time all the resources linked to the same request are finished loaded, I would like to measure this time and then send it to the beacons. But I don't need to have the details of each resource, just the package.
Can Boomerang handle it ? Or be customize for that ?

**Comment by andreas-marschke** [comment]
Yup you can do that. Checkout AutoXHR (`plugins/auto-xhr.js`). 

Network requests executed on the page and subsequent resources can be measured that way.

**Comment by CapucinePr** [comment]
Yes, it seems adapted to my case.
Thanks a lot for your help !

**Comment by andreas-marschke** [comment]
Cool! Closing this ticket then :)

**Comment by nicjansma** [comment]
Small point of clarification, Boomerang should easily be able to measure a click on a link in one app (App1) that opens a page to another app (App2) via the NavigationTiming API, which reports on the performance of full page navigations.  As long as App2 is opened via any link in App1, Boomerang should measure the page load timing OK.

(this wouldn't work in older browsers that [don't support NavigationTiming](https://caniuse.com/#feat=nav-timing))

**Comment by bluesmoon** [comment]
That requires that boomerang be on both apps, right?

**Comment by nicjansma** [comment]
Maybe I'm misunderstanding the scenario, but it sounded like he's just describing a regular (traditional) browser navigation between two "apps".

**Comment by andreas-marschke** [comment]
@capucinepr see above

**Comment by CapucinePr** [comment]
In fact I need to measure the navigation between two different apps. When we click on a link in App1, a new tab is opened for App2.
Moreover, I am not sure to understand everything for auto-xhr : It detects which resources are generated by the same request (thanks to the trie)? And then measure the time spent between the beginning of the first resource of the bundle and the end of the last one ?

**Comment by nicjansma** [comment]
@CapucinePr we're in the middle of updating some of our documentation around AutoXHR.  Can you please review http://dev.nicj.net/boomerang-doc/BOOMR.plugins.AutoXHR.html and let us know if that helps with your questions?
