### ISSUE TITLE
AutoXHR Running Filter

### ISSUE THREAD

**Issue by CapucinePr** [SOASTA/boomerang#155]
I have an application with different pages for which I implemented Boomerang with the plugings restiming, rt, navtiming and auto-xhr.
It works well, except that for some requests, I get this message on the chrome console : 
boomerang.AutoXHR: [debug] Running filter: shouldExcludeXhr on URL: myURL
And there is no beacon sent..
I didn't find how to disable this filter, and to allow beacons to be created for these requests, does someone have a tips ?

**Comment by andreas-marschke** [comment]
Hey @CapucinePr !

Did you adda  BOOMR.xhr_exclude value to your page somewhere? 

Did you recently pull from the master repository (Just so we can gauge what version of the code you're working with)? 

To me this log entry sounds like there's either BOOMR.xhr_exclude on your page that you're using to prevent some XHRUrls from sending a beacon yet in your case it blocks more than it should? 

Do you have a demo page to show what you've done?

Kind regards,

Andreas.

**Comment by CapucinePr** [comment]
Hi,

No I didn't add any BOOMR.xhr_exclude, and I took the files last week so I think they are up to date..
In fact the message is displayed on the console, but for some requests a beacon is sent but for some others no.

**Comment by andreas-marschke** [comment]
Okay, did you use `BOOMR.plugins.AutoXHR.addExcludeFilter` in your code?

**Comment by CapucinePr** [comment]
No I didn't. I just changed the SPA_TIMEOUT from 1000 to 10, and it seems that now everything is working well !

**Comment by bluesmoon** [comment]
Setting SPA_TIMEOUT to 10 will end up not capturing all assets related to the SPA navigation.

**Comment by CapucinePr** [comment]
That's right, but my application is not a SPA, it only has some Ajax requests, for which I want the measure of the xmlhttprequest sent.
So, for the moment, it is the only solution I found..
