### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by buildscientist** [SOASTA/boomerang#157]
Doc links on the Boomerang website are broken. 

Examples: 
- [Use Cases](https://soasta.github.io/boomerang/doc/tutorial-use-cases.html)

- [How it works](https://soasta.github.io/boomerang/doc/tutorial-methodology.html)

**Comment by buildscientist** [comment]
Not sure if the [docs](https://yahoo.github.io/boomerang/doc/) on this Yahoo github page are current.

**Comment by bluesmoon** [comment]
we don't control the yahoo github page, that's considered obsolete.  Can you tell me where you found the other links? I can fix them.

**Comment by bluesmoon** [comment]
nvm, found them

**Comment by bluesmoon** [comment]
I've fixed them, but I can't convince github to regenerate the use-cases.html page from the markdown source, or maybe to flush its cache.

**Comment by buildscientist** [comment]
@bluesmoon Cheers - I believe the GitHub Pages CDN takes a while to propagate.  Looks good thus far 👍
