### ISSUE TITLE
Excluding XHR requests by partial URI

### ISSUE THREAD

**Issue by buildscientist** [SOASTA/boomerang#161]
Hello - Boomerang rocks and so does all the open source work all of you have done on it. 

Is there any way for me to exclude XHR requests by a partial URI? 

Example: 

```json
BOOMR.init({
	beacon_url: "https://example.com/?channel=12345"
	beacon_auth_token: "12345",
	beacon_type: "POST",
	instrument_xhr: true,
	xhr_excludes: "/foo/bar",
	History: {
		enabled: true,
		auto: true
	},
});
```
I have an SPA instrumented that makes periodic calls to an endpoint. The endpoint responds within a specific window so if calls fall outside that window Boomerang reports the DOM as having taken that amount of time to load. 

I did see some comments in #155 regarding setting BOOMR.xhr_excludes - but I'm not sure if this requires a full URL or if partials are supported. 

Thanks!

**Comment by bluesmoon** [comment]
`xhr_includes` currently works with either the full url or the full hostname or the full path. You can't do a partial path as that would be slow (ie, we'd have to iterate through all options and do a regex match rather than a hash lookup).

**Comment by buildscientist** [comment]
@bluesmoon Thanks. By full path do you mean given a URL of: 

http://localhost:8080/foo/bar that the full path is /foo/bar or ?

**Comment by buildscientist** [comment]
Actually I just realized I could get the full URL by writing a plugin that grabs window.location.href and appends the list of URL's in xhr_excludes - in which case partials aren't needed.

**Comment by bluesmoon** [comment]
That's correct.  Note that just appending to `window.location.href` does not work in all cases.  The correct way to do it is this:

```javascript
var a = document.createElement("A");  // make sure document is the actual document object and not from an iframe
a.href = "relative url that you want";
// now read back a.href, it will be an absolute url
```

This also handles cases where `BASE HREF` has been overridden on the page (eg: jquery does this).

**Comment by buildscientist** [comment]
@bluesmoon 
Reopening this issue just so I can get a better understanding of how this works. 

If I specify a URL to BOOMR.xhr_excludes - does the AutoXHR plugin look for HREF strings that match in the document - or is this any XHR call made to the URL in BOOMR.xhr_excludes? 

For some reason I am unable to get the AutoXHR plugin to filter out the request even with the aforementioned solution of concatenating window.location.href

**Comment by buildscientist** [comment]
Managed to figure this out after digging through code. 

For anyone looking to do this the Auto-XHR plugin expects the BOOMR.xhr_excludes object to include a property that _matches_ either anchor.href,anchor.hostname or anchor

Example:
```json

var filteredURL = document.createElement("A");
filteredURL.href = "/uri/you/want/to/filter";

BOOMR.init({
	beacon_url: "https://example.com/?channel=12345"
	beacon_auth_token: "12345",
	beacon_type: "POST",
	instrument_xhr: true,
	History: {
		enabled: true,
		auto: true
	},
});

BOOMR.xhr_excludes[filteredURL.href] = filteredURL.href;

```
The value of the property doesn't matter in this case. 

@bluesmoon I'll see if I can get around to writing a doc for this because getting this setup is **_not_** intuitive.

**Comment by andreas-marschke** [comment]
Hey @buildscientist the AutoXHR plugin also supports addExcludeFilter () have  a look at the jsdoc string in plugins/auto-xhr.js this should be easier for partial matching and custom behaviour.

Kind regards,

Andreas.

**Comment by buildscientist** [comment]
@andreas-marschke - yep I saw that in the code. The functionality in the existing filter function meets my requirements. 

Thanks,
-Y

**Comment by satya-ip** [comment]
Is there a way to add auth token for Get Call?

**Comment by andreas-marschke** [comment]
@satya-ip Your question merits its own ticket as it has nothing to do with the issue talked about here. Please open a new issue if you have questions.
