### ISSUE TITLE
boomerang package for OpenACS

### ISSUE THREAD

**Issue by gustafn** [SOASTA/boomerang#178]
This is not an issue, but a comment: boomerang is now available also as a plugin for OpenACS
https://openacs.org/forums/message-view?message_id=5387444

many thanks for boomerang and its continued development!

**Comment by bluesmoon** [comment]
Great news, thanks for this.

**Comment by nicjansma** [comment]
Wonderful @gustafn !  We'll be adding an "integrations" page for the documentation and will add this.
