### ISSUE TITLE
Page load time after route change

### ISSUE THREAD

**Issue by ibarkowski** [SOASTA/boomerang#179]
Hi, I have a problem with boomerang implementation in my react application. On hard load beacon is send ok, but when application route is changed then in beacon I see metrics calculated not from route change but from last hard page load. For example:
t_resp=5683
t_page=13769299
t_done=13774988
t_other=boomerang|13769283,boomr_fb|6726
Is it a bug or I'm doing something wrong?

**Comment by querymetrics** [comment]
@ibarkowski Do you have a public site where we can reproduce the issue?

**Comment by ibarkowski** [comment]
No. I only test boomerang on my development environment.

**Comment by ibarkowski** [comment]
The problem occurs only when http.initiator=spa_hard.

**Comment by nicjansma** [comment]
@ibarkowski We'd really need a site to dig in to debug this.  If you have a private site you'd be able to share, feel free to email me: nic@nicj.net

**Comment by nicjansma** [comment]
@ibarkowski We've posted some additional bug fixes in https://github.com/SOASTA/boomerang/pull/188.  If you are still having an issue, please let us know (a repro site will help us investigate)
