### ISSUE TITLE
Official Docs?

### ISSUE THREAD

**Issue by buildscientist** [SOASTA/boomerang#181]
Hello, 

What are the official docs for this project? 

[GitHub Docs](https://soasta.github.io/boomerang/doc/) or [SOASTA Boomerang API](https://docs.soasta.com/boomerang-api/) ?

**Comment by bluesmoon** [comment]
both.  the latter is identical to the README file.

**Comment by nicjansma** [comment]
@buildscientist The first link on `https://soasta.github.io/boomerang/doc/` is up to date with this repository's source code.

We've been working on a completely updated Boomerang API documentation, and that is published at `https://docs.soasta.com/boomerang-api/` as you found.  We will be backporting these changes to this repository soon, and at that point, `https://soasta.github.io/boomerang/doc/` will be updated as well.
