### ISSUE TITLE
chrome.LoadTimes is deprecated

### ISSUE THREAD

**Issue by JonHouse** [SOASTA/boomerang#183]
Hi,

Sorry if this has been brought up already, I am getting errors coming from the navtiming plugin (line 192) telling me that chrome.loadTimes() is deprecated: 

chrome.loadTimes() is deprecated, instead use standardized API: nextHopProtocol in Navigation Timing 2.

chrome.loadTimes() is deprecated, instead use standardized API: Navigation Timing 2.

chrome.loadTimes() is deprecated, instead use standardized API: Paint Timing.

Then linking to here: [https://www.chromestatus.com/features/5637885046816768](https://www.chromestatus.com/features/5637885046816768)

Thanks,

~Jon

**Comment by bluesmoon** [comment]
yes, dup of #182, see there for explanation
