### ISSUE TITLE
Errors plugin reports errors that dont exist or are not visible

### ISSUE THREAD

**Issue by golddiga** [SOASTA/boomerang#184]
It seems as if the errors plugin is suppressing error messages in chrome and firefox. Whenever we disable the errors plugin we see error messages on the console. But if we enable it errors disappear. We use the latest errors.js of today.

this is our config:

```
BOOMR.init({
  log: false,
  Errors: {
      enabled: true,
      sendAfterOnload: true,
      monitorGlobal: true,
      monitorNetwork: true,
      monitorConsole: true,
      monitorEvents: true,
      monitorTimeout: true,
      maxErrors: 100
  }
});
```
Console:
<img width="1148" alt="screen shot 2018-02-19 at 19 16 18" src="https://user-images.githubusercontent.com/5981129/36392020-7c870fbc-15a9-11e8-8306-9e419982ca9d.png">

Error in Beacon:

<img width="854" alt="36392021-7c9ea500-15a9-11e8-9bb3-34c54ed672f7" src="https://user-images.githubusercontent.com/5981129/37208626-513d54ae-23a2-11e8-963f-fa24ebf6d075.png">

**Comment by nicjansma** [comment]
Hi Mike!  I'm in the middle of back-porting fixes we've made for the last year.  We should have a PR open with a fix for the above issue in a week or so.

**Comment by nicjansma** [comment]
Merged!
