### ISSUE TITLE
Is Boomerang has declaration file？  d.ts

### ISSUE THREAD

**Issue by Anna-mm** [SOASTA/boomerang#186]

**Comment by Anna-mm** [comment]
Hi,
I want Boomerang to monitor Angular 2+ Application。so Is Boomerang has declaration file for TS？Are there any plan to do it? Any solution for Angular 2+ Application . I will appreciate your answer. Thank you.

**Comment by nicjansma** [comment]
Hi Anna-mm,

We do not currently have plans to add a TypeScript declarations file.  You might be able to use something like https://github.com/brettle/jsdoc-to-typescript-declaration once we merge in an update JSDoc update for Boomerang (coming soon!).

Boomerang supports monitoring AngularJS2 applications via the [History plugin](http://docs.soasta.com/boomerang-api/BOOMR.plugins.History.html)
