### ISSUE TITLE
Error Plugin: Override of addEventListener and removeEventListener breaks when using options as third argument

### ISSUE THREAD

**Issue by MoritzKn** [SOASTA/boomerang#187]
Reproducible with this code:

```js
function test() {
	console.log('test')
}
document.body.addEventListener('click', test, { passive: true });
document.body.removeEventListener('click', test);
```

The event listener will be added but not removed.

The problem here is that the error plugin overrides the remove event listener function of `Element.prototype`, `window`and `XMLHttpRequest.prototype`. The new function that overrides `addEventListener` [tracks added event listeners](https://github.com/bluesmoon/boomerang/blob/66e7e3de294cfbfee46d05b6656a7565a44bfd66/plugins/errors.js#L843) to be able to remove the actual listener and not the wrapped callback function later. It however assumes that the third argument is `useCapture` with a boolean value. It is not able to work with an `options` object as third argument ([See addEventListener on MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener)).

If the third argument is an object it will be [converted to a boolean](https://github.com/bluesmoon/boomerang/blob/66e7e3de294cfbfee46d05b6656a7565a44bfd66/plugins/errors.js#L878) before being stored in the array tracking all event listeners, resulting in a `true` value for `useCapture` .
If the new function for `removeEvenListener` then [tries to retrieve](https://github.com/bluesmoon/boomerang/blob/66e7e3de294cfbfee46d05b6656a7565a44bfd66/plugins/errors.js#L927) the function again, the functio [asserts that `useCapture` has the same (boolean) value](https://github.com/bluesmoon/boomerang/blob/66e7e3de294cfbfee46d05b6656a7565a44bfd66/plugins/errors.js#L906). However since only the `useCapture`/`options.capture` flag is relevant when removing event listeners, the options may be omitted when removing the event listeners again, resulting in a falsy `useCapture` value.

The workaround for this is to always pass an option object when calling `removeEventListener`:
 ```js
function test() {
	console.log('test')
}
document.body.addEventListener('click', test, { passive: true });
document.body.removeEventListener('click', test, {});
```

However this is not possible for third party code, resulting in broken libraries. For example [noUiSlider](https://refreshless.com/nouislider/) breaks through this bug.

**Comment by bluesmoon** [comment]
Just pushed 6b19b896baa6c46ac215295b711f0474c4bc36be which fixes this.

**Comment by MoritzKn** [comment]
Could you say something about the release process?
Do you happen to know something about https://c.go-mpulse.net/boomerang? Thats what the website I am working with uses to embed boomerang.

**Comment by bluesmoon** [comment]
Ah, in that case you're looking at the commercial product mPulse.  The website owner will have to contact their support person and ask for an upgrade.  I think the fix for this is available in one of the newer limited availability versions, which means the site needs to explicitly ask for the upgrade.
