### ISSUE TITLE
SPA - Dynamic URL images not properly handled

### ISSUE THREAD

**Issue by adrienbu** [SOASTA/boomerang#189]
Hi,

When I have an image with dynamic URL, its loading time does not seem to be properly counted on soft page changes. Indeed, in the following code from "auto-xhr" plugin, I think there is a bug.

```
if (node._bmr && node._bmr.res && node._bmr.end[node._bmr.res]) {
	exisitingNodeSrcUrlChanged = true;
}
```
If the node is an image and was already loaded previously, node._bmr would be initialized, node._bmr.res value would be 0 and node._bmr.end[node._bmr.res] wouls be initialized to last time load. So exisitingNodeSrcUrlChanged should be true and all the waiting process with eventListener and nodes_to_wait incrementation should be done.
However because node._bmr.res value is 0, it is considered falsy and exisitingNodeSrcUrlChanged is set to false and therefore, we do not wait for this ressource.

I believe this is a bug. I have a plunker to reproduce this.
https://plnkr.co/DkFJlOMBP1TCC8Zzppl8

When you switch tab, state is changing and image as well. If you put yourself in slow 3G, first time you switch tab, you can see in console the "SENDING BEACON" log indicating that beacon would be sent to the server, before image is actually loaded.

I believe the code should be 
```
if (node._bmr !== undefined && node._bmr.res !== undefined && node._bmr.end[node._bmr.res] !== undefined) {
	exisitingNodeSrcUrlChanged = true;
}
```

Note: I was actually trying to reproduce another bug I have with Iframe. So if you only do the fix I propose, you will encounter the other issue I was running into with Iframe. I'll create another issue for this bug once I have a sample to reproduce.

**Comment by bluesmoon** [comment]
Thanks for the great report.  I'd probably change to use `typeof(node._bmr.res) !== "number"`, but the rest looks good.

**Comment by querymetrics** [comment]
@adrienbu Hi, can you try the `soasta-2018` branch, see: https://github.com/SOASTA/boomerang/pull/188. It contains a fix similar to what you propose.

**Comment by querymetrics** [comment]
Also, would you be able to try this WIP patch which should better track node `src` changes? :
https://gist.github.com/querymetrics/7940da0ca577f07dec918a2ee1c72bc0

**Comment by adrienbu** [comment]
Indeed fix seems similar. I'll try the branch and your patch. Thanks for the quick answer.

**Comment by adrienbu** [comment]
I am not able to build the branch. Launching grunt gives me the error `>> TypeError: Cannot read property 'length' of undefined``
I tried to just concat all plugins I was using together but I'm not able to make it work. Can you help ?

**Comment by nicjansma** [comment]
@adrienbu Please give the latest commits in `soasta-2018` a try for building.

**Comment by adrienbu** [comment]
@nicjansma actually I figured out what I was doing wrong just before you posted. I was including auto_xhr after the SPA plugin... Your new commit with plugin in the correct order works perfectly. It fixes the issues I had so thanks a lot, I'll close this.

However my remark about event listener remains true. I've just tested it with a breakpoint inside the `load_cb` function of auto_xhr plugin and it gets called many times at each page navigation (once after first page change, twice after the second...). It could cause performance issues for long navigation sessions inside a SPA.

I would change this code
```
node.addEventListener("load", function(ev) { self.load_cb(ev, resourceNum); });
node.addEventListener("error", function(ev) { self.load_cb(ev, resourceNum); });
```
with something like this
```
// Clean up existing event listener
if (node.boomrAutoxhrEventListener) {
	node.removeEventListener("load", node.boomrAutoxhrEventListener);
	node.removeEventListener("error", node.boomrAutoxhrEventListener);
}

node.boomrSpaEventListener = function(ev) { self.load_cb(ev, resourceNum); };
node.addEventListener("load", node.boomrAutoxhrEventListener);
node.addEventListener("error", node.boomrAutoxhrEventListener);
```

**Comment by querymetrics** [comment]
@adrienbu Thanks, can you copy your last comment into a new issue and we'll investigate
