### ISSUE TITLE
No PAYLOAD data

### ISSUE THREAD

**Issue by milal1ca** [SOASTA/boomerang#191]
Hi,
I'm new with BOOMERANG.
A few days ago, I realized that I was working with an old version of boomerang.js, so I downloaded the new version. The old version worked well, as expected. With the new version, the behavior of HTTP requests is different. With the old version, the default query type was GET. Now it's POST. If I force beacon_type = "GET", it does not work. It always use POST. I only use the RT plugin to ensure that the amount of data is small. Then the PAYLOAD (Form Data) no longer appears in the Chrome development console (IE gives the same problem). I know, however, that the beacon is correctly transferred to my web server. I use basic code in synchronous mode

**Comment by milal1ca** [comment]
My code is: 
`<html>
<head>
  <script src="boomerang/boomerang.js"></script>
  <script src="boomerang/plugins/rt.js"></script>
  <script>
    BOOMR.init({
	  beacon_url: "/boomerang_handler"
	});
  </script>
</head>
<body>
<h1>It works! Mike</h1>
</body>
</html>`

**Comment by milal1ca** [comment]
`<html>
<head>
  <script src="boomerang/boomerang.js"></script>
  <script src="boomerang/plugins/rt.js"></script>
  <script>
    BOOMR.init({
	  beacon_url: "/boomerang_handler"
	});
  </script>
</head>
<body>
<h1>It works! Mike</h1>
</body>
</html>`

**Comment by milal1ca** [comment]
QueryMetrics,
You're right, Chrome Canary 68 solved my Payload problem. Thanks.
Should I understand the GET request is no longer a valid option?

**Comment by querymetrics** [comment]
If you really don't want to use sendBeacon for some reason, you can remove the section here https://github.com/SOASTA/boomerang/blob/master/boomerang.js#L3284 in your build. If the payload is too large then it needs to be sent with POST regardless

**Comment by milal1ca** [comment]
Thank you QueryMetrics, 
I close this case

**Comment by rolaso** [comment]
Interesting topic, as we just had a similar experience after upgrading to the latest version of Boomerang. 

Our problem was that we can't use POST without having to make some infrastructure changes to get the POST data. We took off plugins we didn't need (that now come included), and it reverted to GET.

If I understand Nigel's reply, and for future reference, we can make the decision ourselves by not using sendBeacon()? Then see how much payload we can get away with sending via GET?

Thank you,

**Comment by milal1ca** [comment]
Rolaso,
Which pluing did you took off and how did you do it? In my case, I only use the followings:
`<script src="boomerang/boomerang.js"></script>
  <script src="boomerang/plugins/rt.js"></script>`
Plugins I use and data generated could not be smaller than that, I think?

**Comment by rolaso** [comment]
ResourceTiming. 

You can choose which plugins you want to use. Take a look at the documentation page: https://docs.soasta.com/boomerang-api/tutorial-building.html

Says to modify plugins.json with the ones you want.

Good luck!
