### ISSUE TITLE
Version Sept 7th, 2017 introduced a problem with those combined plugins: SPA, XHR, Angular

### ISSUE THREAD

**Issue by milal1ca** [SOASTA/boomerang#192]
Hi,
I use Boomerang and the following plugins: SPA, Angular, XHR and RT.
Wanting to use the latest version of Boomerang I realized that there was possibly a Bug with this new version. After a few tests I discovered that the version of September 7th, 2017 had introduced a problem. 
Any version prior Sept 7th works well.
With new version, Beacon is not sent.

The code added in SPA.js plugin was:

`BOOMR = window.BOOMR || {};
BOOMR.plugins = BOOMR.plugins || {};
if (BOOMR.plugins.SPA || !BOOMR.plugins.AutoXHR) {
	return;
}`

Here is HTML/Javascript I used. You can try it easily. The only thing you have to do is to replace the location of the Boomerang's directory. 

[Boom_Test.txt](https://github.com/SOASTA/boomerang/files/1932207/Boom_Test.txt)

Errors calling my Perl script (XHR) make no difference. 

Regards,
Michel

**Comment by nicjansma** [comment]
@milal1ca the `SPA` plugin [depends](https://soasta.github.io/boomerang/BOOMR.plugins.SPA.html) on the `AutoXHR` plugin.  Can you add that to your `plugins.json`?

**Comment by nicjansma** [comment]
Ah, I see now:

```
    <script src="boomerang_082017/boomerang.js"></script>
    <script src="boomerang_082017/plugins/rt.js"></script>
    <script src="boomerang_082017/plugins/spa.js"></script>
    <script src="boomerang_082017/plugins/angular.js"></script>
    <script src="boomerang_082017/plugins/auto-xhr.js"></script>
```

Change this order to:

```
    <script src="boomerang_082017/boomerang.js"></script>
    <script src="boomerang_082017/plugins/rt.js"></script>
    <script src="boomerang_082017/plugins/auto-xhr.js"></script>
    <script src="boomerang_082017/plugins/spa.js"></script>
    <script src="boomerang_082017/plugins/angular.js"></script>
```

**Comment by milal1ca** [comment]
Problem is now solved !!!!
Thank you for this quick response.
Was it documented like that ?
Regards,
Michel

**Comment by nicjansma** [comment]
Good!

Each plugin should document its own dependencies: https://soasta.github.io/boomerang/BOOMR.plugins.SPA.html
