### ISSUE TITLE
npm story

### ISSUE THREAD

**Issue by AndreyNikiforov** [SOASTA/boomerang#193]
I noticed that SOASTA is now officially releasing boomerangjs (https://github.com/SOASTA/boomerang/releases/tag/1.568.0) and updating npm package (https://www.npmjs.com/package/boomerangjs). Is this a direction going forward (a change from https://github.com/SOASTA/boomerang/issues/108)?

What is the support for npm and how boomerangjs can be used with npm?

**Comment by nicjansma** [comment]
Hi @AndreyNikiforov !

Yes -- we're going to synchronize the open-source Boomerang's version number (this repository) with the mPulse-specific Boomerang we work on daily at SOASTA/Akamai.  We'll release new versions to this repo after each set of backports from our Akamai code (which we're aiming to do a couple times a year).

Boomerang is just being published as-is (from this repository) on NPM.  You may need to overwrite the `plugins.json` with your own needs, or patch files if you have specific changes.
