### ISSUE TITLE
Error plugin?

### ISSUE THREAD

**Issue by philbooth** [SOASTA/boomerang#30]
I guess this may be out of scope for boomerang; it's not performance-related although it is RUM.

But would there be any interest in a plugin that reports a simple count of the unhandled JavaScript errors caught by `window.onerror`?

We measure this outside of boomerang at the moment, sending an aggregate count to our back-end on load and then sending any further increments as they occur. A graph of the mean count is a useful indicator because there are so many ways for a JS payload to break and affect the page, of which we'd otherwise be unaware.

Of course, it's no problem for us to continue doing this separately, but if you thought there might be a place for it here, I'm happy to put something together.

**Comment by sridharangopal** [comment]
Hi all, Just trying to get the latest on this. I was looking for the error plugin. Is the one referenced by andreas the only error plugin that we can use currently with the latest version of Boomerang?

**Comment by nicjansma** [comment]
Hi @sridharangopal, SOASTA is currently testing a new Error plugin that will capture `window.onerror` and more.  It should be included in the next round of things we backport to the open-source repo.

**Comment by sridharangopal** [comment]
Great ... thanks for the update @nicjansma ... Any idea on the eta on this plugin to the open-source repo?

**Comment by nicjansma** [comment]
Error plugin is available in https://github.com/SOASTA/boomerang/pull/98
