### ISSUE TITLE
lognormal\boomerang not registered with bower

### ISSUE THREAD

**Issue by ryandle** [SOASTA/boomerang#61]
GET http://bower.herokuapp.com/packages/boomerang

Result:
{"name":"boomerang","url":"git://github.com/bluesmoon/boomerang.git","hits":127}

According to this pull request, it looks like the intention was to register the lognormal\boomerang repo?

https://github.com/lognormal/boomerang/pull/36

**Comment by bluesmoon** [comment]
unfortunately no one from the boomerang team actually registered the package with bower.  It was done by someone else and we don't know how to change it.

**Comment by nicjansma** [comment]
Hey @josh, any chance you can help us with this?  You had helped before me with https://github.com/nicjansma/usertiming.js/pull/4.  We'd like to redirect the bower info for boomerang to lognormal/boomerang.

**Comment by bluesmoon** [comment]
bower token login doesn't work.  Waiting for them to fix that first.

**Comment by nicjansma** [comment]
We've been able to update https://bower.herokuapp.com/packages/boomerang
