### ISSUE TITLE
error thrown as 'this.session' is undefined

### ISSUE THREAD

**Issue by luckykurhe** [SOASTA/boomerang#88]
error thrown as `this.session` is undefined, when `site_domain` is provided as an option from config.
looking at the code `this.session.domain` is not used anywhere, so removing might be ok.
ref: https://github.com/SOASTA/boomerang/blob/master/boomerang.js#L783
PR: https://github.com/SOASTA/boomerang/pull/87
Please let me know if its not the case

**Comment by nicjansma** [comment]
Yep great find, thanks!
