### ISSUE TITLE
Is there a plugin for ReactJS for SPA

### ISSUE THREAD

**Issue by luckykurhe** [SOASTA/boomerang#89]
Is there a SPA plugin for ReactJS pages to capture view timings,
similar to AngularJS, BackboneJS plugins

**Comment by andreas-marschke** [comment]
We have one planned to be merged into the OSS repo. Depends on when we get the time to prepare it.

**Comment by luckykurhe** [comment]
thx, plz let me know if I can help with any tasks

**Comment by nicjansma** [comment]
React plugin is available in https://github.com/SOASTA/boomerang/pull/98
