### ISSUE TITLE
`grunt test` failing : missing folder `boomerang/tests/vendor`

### ISSUE THREAD

**Issue by luckykurhe** [SOASTA/boomerang#90]
I am planning to write a new plugin and wanted to make sure that existing test cases are not broken,
but even without any code changes `grunt test` command is failing 

Few files like mocha.css, mocha.js, assertive-chai.js etc.. are referred from `/boomerang/tests/vendor` folder inside `boomerang/tests/unit/index.html` but folder is not available in source code

INFO [karma]: Karma v0.12.37 server started at http://localhost:4000/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket Z0Yd4CSDb0rIU6d47n4A with id 96124815
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: chai

**Comment by andreas-marschke** [comment]
Did you run `bower install`? We have some assets that we depend on to run the tests in phantom/browsers. These assets are installed to `tests/vendor`

**Comment by luckykurhe** [comment]
`bower install` worked, I was trying `npm install` `grunt test` :( . thx.
can close this issue
