### ISSUE TITLE
Modified iframe solution takes over page with empty screen when used with another iframe on same page

### ISSUE THREAD

**Issue by mikeburrelljr** [SOASTA/boomerang#93]
Hello. I'm trying to use Boomerang to determine how much time its taking the current page to load.

I've compiled boomerang.js and the script I'm using to call it is:
`
    (function(document){
        var dom,doc,where,iframe = document.createElement('iframe');
        iframe.src = "javascript:void(0)";
        (iframe.frameElement || iframe).style.cssText = "width: 0; height: 0; border: 0";
        var where = document.getElementsByTagName('script')[0];
        where.parentNode.insertBefore(iframe, where);
        try {
            doc = document;
        } catch(e) {
            dom = document.domain;
            iframe.src="javascript:var d=document.open();d.domain='" + dom + "';void(0);";
            doc = document;
        }
        doc.open()._l = function() {
            var js = this.createElement("script");
            if(dom) this.domain = dom;
            js.id = "js-iframe-async";
            js.src = '/libraries/boomerang/boomerang-0.9.1466026245.js';
            this.body.appendChild(js);
        };
        doc.write('<body onload="document._l();">');
        doc.close();
    })(parent.document);
`

I've modified the original code so that `doc = document;` so that the t_ timings relate to the current page (and not the iframe). I believe this is having the unintended affect of taking over the page with an empty screen when another iframe is already on the page (ie: a media uploader).  Also, my catch is not doing anything different from my try.

Can anyone point me in the right direction for the iframe implementation + how to get the correct page load times for the current page (not the iframe)? Thanks!

**Comment by bluesmoon** [comment]
don't modify the code.  The original code is already designed to measure your page and not the iframe.
