### ISSUE TITLE
Copy boomerang.js and the images/ directory into your document root?!?

### ISSUE THREAD

**Issue by MCArthurKent** [SOASTA/boomerang#94]
I am trying to implement this into an Order Management run locally on our store Tomcat server.The application contains one main.html page but the rest is written in FlexUI. Where do I put the js file and images directory for best performance?

**Comment by bluesmoon** [comment]
You can put it anywhere actually.  For ease of maintenance, maybe make a subdirectory alongside your main.html called `boomerang` and put the js in there, and `boomerang/images` for the images.  For performance, use a CDN, but make sure you configure your CDN to ignore query strings when caching the bandwidth images.  If you don't do that, you'll end up with a huge CDN bill.

**Comment by MCArthurKent** [comment]
Phil, 

Forgive my inexperience but I am having trouble following the howTo guide. So far I have made a the .js and image folders, copied the code for .init() and .subscribe for the BOOMR object went to test it and the .subscribe method is not being reached from my main.html file. My BOOMR object is created but it is not relieving any information What should I do? I have been playing with this for 5 hours and cannot get ahead. Is there a video showing an implementation of Boomerang?

**Comment by bluesmoon** [comment]
Show us the code of your html, and also the steps you used to build boomerang.js.

**Comment by MCArthurKent** [comment]
![image](https://cloud.githubusercontent.com/assets/19961682/16230775/1e0b4e8c-3791-11e6-8466-88f364de3ab6.png)

**Comment by bluesmoon** [comment]
Why is the `, console.log(" BOOMR Initialized")` inside the `BOOMR.init` call?

Also, what was the command used to build boomerang?  Which plugins do you have included?

**Comment by MCArthurKent** [comment]
The console.log is in there to test,  it has been removed. I don't understand what you mean by "command use to build boomerang", please include an example command that would build boomerang. And I am researching how to use a plugin because I had not used any.

**Comment by bluesmoon** [comment]
See step 2 in the readme at
https://github.com/SOASTA/boomerang/blob/master/README.md

At least one plugin is required to add data to the beacon and to actually
send the beacon. Try the rt.js plugin for example.

**Comment by bluesmoon** [comment]
To be clear, you have two options for using boomerang:
   1. add boomerang and all the plugins you need as `<script>` nodes.
   2. Combine boomerang and all the plugins you need into a single file (using the `make` command described in Step 2 of the `README`) and then just include that file.

You MUST do one of these two.  Without any plugins, boomerang will not fire a beacon because it does not know when to fire.  The plugins tell boomerang that they are ready to send data, and that's when boomerang fires the beacon.

**Comment by MCArthurKent** [comment]
Thanks. I got it to work! Do you have a way to work with MXML and ActionScript3 our application only had one HTML file and that is all that we have been able to gather metrics on.

**Comment by bluesmoon** [comment]
I am not familiar with any of those technologies unfortunately.
