### ISSUE TITLE
don't work when switch to https

### ISSUE THREAD

**Issue by artbels** [SOASTA/boomerang#95]
BOOMR.subscribe('before_beacon', function(o) {
returns only {u: "https://map.multitest.ua/", v: "0.9", vis.st: "visible"}

BOOMR.init({
      beacon_url: "",
      site_domain:  "https://map.multitest.ua",
      BW: {
        base_url: 'https://map.multitest.ua/vendor/boomerang/images/',
        block_beacon: true,
        cookie_exp: 1
      }
    });

**Comment by bluesmoon** [comment]
Have you added any plugins to your boomerang build?

**Comment by artbels** [comment]
I load only

  <script src="vendor/boomerang/boomerang.js"></script>
  <script src="vendor/boomerang/plugins/bw.js"></script>

**Comment by bluesmoon** [comment]
the bandwidth test does not work over https.

**Comment by bluesmoon** [comment]
See https://soasta.github.io/boomerang/doc/api/BW.html for details on how to use the BW plugin.

**Comment by artbels** [comment]
OK, thanks for answer!
