### ISSUE TITLE
Need help on Anguarjs plugin

### ISSUE THREAD

**Issue by Rakesh181032** [SOASTA/boomerang#96]
I am trying to capture angularjs performance statistics using boomerang but looks like plugin initialization is not successful ... can you please take look at below example and help here.. if availble please share link for examples on angularjs with boomerang 

```
---------------------------------------------------------------------------------
app.js
---------------------------------------------------------------------------------
var app = angular.module('myApp', ['ngRoute']);

angular.module('myApp')
    .run(['$rootScope', function($rootScope) {
        var hadRouteChange = false;

        $rootScope.$on("$routeChangeStart", function() {
           
            hadRouteChange = true;
        });
 
        function hookAngularBoomerang() {
        
            if (window.BOOMR && BOOMR.version) {
					  alert(BOOMR.plugins.Angular)
                if (BOOMR.plugins && BOOMR.plugins.Angular) {
                     
                    BOOMR.plugins.Angular.hook($rootScope, hadRouteChange);
                }
                
                return true;
            }
        }

        if (!hookAngularBoomerang()) {
          
            if (document.addEventListener) {
             
                document.addEventListener("onBoomerangLoaded", hookAngularBoomerang);
            } else if (document.attachEvent) {
              
                document.attachEvent("onpropertychange", function(e) {
                    e = e || window.event;
                    if (e && e.propertyName === "onBoomerangLoaded") {
                        hookAngularBoomerang();
                    }
                });
            }
        }
    }]);
```

```
app.config(function($routeProvider) {
  $routeProvider

  .when('/', {
    templateUrl : 'pages/home.html',
    controller  : 'HomeController'
  })

  .when('/blog', {
    templateUrl : 'pages/blog.html',
    controller  : 'BlogController'
  })

  .when('/about', {
    templateUrl : 'pages/about.html',
    controller  : 'AboutController'
  })

  .otherwise({redirectTo: '/'});
});

app.controller('HomeController', function($scope) {
  $scope.message = 'Hello from HomeController';
});

app.controller('BlogController', function($scope) {
  $scope.message = 'Hello from BlogController';
});

app.controller('AboutController', function($scope) {
  $scope.message = 'Hello from AboutController';
});
```

```
------------------------------------------------------------------------------------------------------------
HTML file
------------------------------------------------------------------------------------------------------------
```
```
<html ng-app="myApp">
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular-route.min.js"></script>
        <script src="app.js"></script>
<head>

<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="../boomerang-docs.css">
</head>
<body>
  </head>
  <body>
    <script type="text/ng-template" id="pages/home.html">
      <h1>Home</h1>
      <h3>{{message}}</h3>
    </script>
    <script type="text/ng-template" id="pages/blog.html">
      <h1>Blog</h1>
      <h3>{{message}}</h3>
    </script>
    <script type="text/ng-template" id="pages/about.html">
      <h1>About</h1>
      <h3>{{message}}</h3>
    </script>
    <a href="#/">Home</a>
    <a href="#/blog">Blog</a>
    <a href="#/about">About</a>
    <div ng-view></div>


<p id="results">
</p>
  </body>
</html>


<p id="results">
</p>

<script src="http://www.lognormal.com/boomerang/boomerang.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/plugins/bw.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/plugins/navtiming.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/plugins/rt.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/doc/howtos/howtos.js" type="text/javascript"></script>
<script src="myangular.js" type="text/javascript"></script>
<script src="spa.js" type="text/javascript"></script>
<script type="text/javascript">
BOOMR.init({ 
alert('BOOMR.plugins.NavigationTiming')
		Angular:{		
						enabled: true				
			},
    autorun: false,							
	// Disable XHR instrumentation as this is auto-enabled by the SPA-plugins 
	instrument_xhr: false
	});
</script>
</body>
</html>
```

**Comment by Rakesh181032** [comment]
<html ng-app="myApp">
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular-route.min.js"></script>
        <script src="app.js"></script>
<head>

<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="../boomerang-docs.css">
</head>
<body>
  </head>
  <body>
    <script type="text/ng-template" id="pages/home.html">
      <h1>Home</h1>
      <h3>{{message}}</h3>
    </script>
    <script type="text/ng-template" id="pages/blog.html">
      <h1>Blog</h1>
      <h3>{{message}}</h3>
    </script>
    <script type="text/ng-template" id="pages/about.html">
      <h1>About</h1>
      <h3>{{message}}</h3>
    </script>
    <a href="#/">Home</a>
    <a href="#/blog">Blog</a>
    <a href="#/about">About</a>
    <div ng-view></div>


<p id="results">
</p>
  </body>
</html>


<p id="results">
</p>

<script src="http://www.lognormal.com/boomerang/boomerang.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/plugins/bw.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/plugins/navtiming.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/plugins/rt.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/doc/howtos/howtos.js" type="text/javascript"></script>
<script src="myangular.js" type="text/javascript"></script>
<script src="spa.js" type="text/javascript"></script>
<script type="text/javascript">
BOOMR.init({ 
alert('BOOMR.plugins.NavigationTiming')
		Angular:{		
						enabled: true				
			},
    autorun: false,							
	// Disable XHR instrumentation as this is auto-enabled by the SPA-plugins 
	instrument_xhr: false
	});
</script>
</body>
</html>

**Comment by Rakesh181032** [comment]
<script src="http://www.lognormal.com/boomerang/boomerang.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/plugins/bw.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/plugins/navtiming.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/plugins/rt.js" type="text/javascript"></script>
<script src="http://www.lognormal.com/boomerang/doc/howtos/howtos.js" type="text/javascript"></script>
<script src="myangular.js" type="text/javascript"></script>
<script src="spa.js" type="text/javascript"></script>
<script type="text/javascript">
BOOMR.init({ 
alert('BOOMR.plugins.NavigationTiming')
		Angular:{		
						enabled: true				
			},
    autorun: false,							
	// Disable XHR instrumentation as this is auto-enabled by the SPA-plugins 
	instrument_xhr: false
	});
</script>

**Comment by Rakesh181032** [comment]
Below lines are added in HTML file
BOOMR.init({ 
alert('BOOMR.plugins.NavigationTiming')
		Angular:{		
						enabled: true				
			},
    autorun: false,							
	// Disable XHR instrumentation as this is auto-enabled by the SPA-plugins 
	instrument_xhr: false
	});

**Comment by andreas-marschke** [comment]
Hey @Rakesh181032 

I've updated your comments to have properly formatted code highlighting based on Githubs Markdown so we can read what your code actually looks like :)

From looking at it there are a few things that are missing/problematic with it:

 - Don't include JS from wild sites in the hope that they will work for your case, [You will run into more trouble with that](https://news.ycombinator.com/item?id=2055567)
```
<script src="http://www.lognormal.com/boomerang/boomerang.js" type="text/javascript"></script>
```
 - from your code I do not see that you have included the Angular plugin for boomerang at all.
 - Use a proper build by compiling it from source into a version `boomerang.js` file

_*Building a Boomerang Release:*_

Clone the Boomerang repository:
```shell
$> git clone https://github.com/SOASTA/boomerang.git
...
$> cd boomerang
```

Install the build dependencies (you will need Nodejs and NPM on your system for that): 
```
$ ~/boomerang/ > npm install .
```
Build with grunt:
```
$ ~/boomerang/ > grunt
```

You will find a `boomerang-<unix-epoch-time-of-build>.js` file in your `build/` directory under the boomerang clones root. Use that in your project. It will have the required Plugins and features already included in it.

Should you wish to remove a set of capabilities feel free to remove that plugin from the `plugins.json` list, but be careful and check that none of the other Plugins require it to work properly.

**Comment by Rakesh181032** [comment]
Thanks Andreas !

Now I am able to collect statistics ... Got few warning initially but able to build.
Is there any document which can help to understand captured information   

Below is out put from my sample app

Hello from HomeController
-----------------------------------------------------------------------------------------------------
This page took 1683 ms to load
Other timers measured: 
   t_domloaded = 640 ms
Other parameters:
   rt.start = manual
   restiming = {"file:///C:/Users/**********/":{"Desktop/":{"test2.html#/":"0,v,v,t,s,,s,s,s","app.js":"3cd,3,,2,2,,2,2,2","CTS/Angular%20rnd/boomerang/build/":{"boomerang-1466864609.js":"3cn,4,,3,3,,3,3,3","plugins/":{"bw.min.js":"3db,3,,2,2,,2,2,2","navtiming.min.js":"3dj,3,,1,1,,1,1,1","rt.min.js":"3dr,2,,1,1,,1,1,1"}},"spa.js":"3g6,4,,3,3,,3,3,3"},"boomerang-docs.css":"2ck,1,,1,1,,1,1,1"},"http":{"s://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular":{".min.js":"3w,89","-route.min.js":"3aq,1g"},"://www.lognormal.com/boomerang/doc/howtos/howtos.js":"3dz,21"}}
   rt.tstart = 1466865361852
   rt.bstart = 1466865362326
   rt.end = 1466865363535
   http.initiator = spa
   nt_req_st = 1466865361852
   nt_domcomp = 1466865362501
   v = 1466864609
   vis.st = visible
   ua.plt = Win32
   ua.vnd = 
-----------------------------------------------------------------------------------------------------
This page took 1106 ms to load
Other parameters:
   rt.start = manual
   restiming = {}
   rt.tstart = 1466865457741
   rt.bstart = 1466865362326
   rt.end = 1466865458847
   http.initiator = spa
   nt_req_st = 1466865457741
   nt_domcomp = 1466865457843
   v = 1466864609
   vis.st = visible
   ua.plt = Win32
   ua.vnd = 
   dom.res = 14
   dom.doms = 3
   scr.xy = 1366x768
   scr.bpp = 24/24
   dom.ln = 51
   dom.sz = 3282
   dom.img = 0
   dom.script = 13
   dom.script.ext = 9
   nu = file:///C:/Users/********/Desktop/test2.html#/blog

**Comment by bluesmoon** [comment]
The online docs have information on all parameters: https://soasta.github.io/boomerang/doc/api/index.html
