### ISSUE TITLE
restiming - not posting data to statsd using boomcatch

### ISSUE THREAD

**Issue by softwareklinic** [SOASTA/boomerang#97]
I understand this is not a boomerang issue --- but still wanted to post here to see if any help can be made available.
We are using boomcatch -- to capture the beacon data and then forward to statsd... we are seeing the navtiming and rt data in statsd but not the restiming....

**Comment by andreas-marschke** [comment]
@softwareklinic Hey! Can you post your `BOOMR.init` parameters and the `plugins.json` that you use to build your version of boomerang with?

If you're not using the newer `grunt`-based Build Task can you tell us what your current Plugins are and if they include the ResourceTiming plugin? (`restiming.js` under `plugins/`).

**Comment by softwareklinic** [comment]
Before i do that - just wanted to provide some additional information - i do see boomerang.js posting below data to the beacon server (boomcatch) - for the restiming -- so looks like a JSON response... 

How would statsd interpret this json.. i do see all all numeric/time data in statsd for nav timing and round trip... but no restiming

{"http":{"://":{"www.xxxxxx.com/":{"search":{"/":{"SearchResults?ES=ResidentialShop&Ntt=dvr+not+working":"0,10p,w9,gb,fj,,fj,fj,fj","css/search_box.css":"21bv,eh,u","views/desktop/VzSearchBox/endeca-auto-suggest.js":"31cq,l0,j4,if,if,,if,if,if,if"},"resources/":{"css/":{"f":{"onts.css":"210h,f8,q","iosSearch.css":"212b,dk,i"},"re":{"sult":{"Content.css":"2xp,hl,t","Tab.css":"2118,ej,l"},"centSearch.css":"213b,cm,j"},"agentHelp.css":"2yi,gw,o","search_box.css":"2z7,g9,l","common.css":"2zt,fp,n","pageResult.css":"211t,e1,i","breadcrumb.css":"212t,d3,h","Vz":{"GuidedNavigation.css":"213u,c4,i","Alert.css":"214c,bo,i"}},"js/":{"r":{"t.js":"317e,91,i","estiming.js":"318d,f6,h"},"jquery":{"-1.4.4.min.js":"314u,b7,m",".cookie.js":"315g,ao,i"},"tealeaf.js":"315y,a7,h","global.js":"316f,9s,i","boomerang.js":"316x,9h,h","navtiming.js":"317w,fk,h"}}},"home/ak-cached/2h/javascript/":{"commons.js":"318u,er,i|327n,1b,q","myvzconsole.js":"31bc,ex,h|32b0,12,k"},"includes/javascript/omnicode.js":"319c,ec,h|329m,r,l"},"assets.adobedtm.com/10d5272d092923c410feae744225087686012423/":{"satelliteLib-8df7d93db820b272138ecb04dbe4ed7f5023b893.js":"319t,ez,h","mbox-contents-38b8f99ca10f023c55557c0e31691691b2737750.js":"31tk,1j,13"},"cdn.tt.omtrdc.net/cdn/target.js":"31wd,1q","verizontelecom.tt.omtrdc.net/m2/verizontelecom/mbox/ajax?mboxHost=www.xxxxxx.com&mboxPage=1466808347554-598039&screenHeight=900&screenWidth=1440&browserWidth=1200&browserHeight=308&browserTimeOffset=-300&colorDepth=24&mboxSession=1466808175400-610371&mboxPC=1465966949925-738790.20_32&mboxMCGVID=55742958695673943888387616320534172117&mboxAAMB=hmk_Lq6TPIBMW925SPhw3Q&mboxMCGLH=7&mboxCount=1&mboxTime=1466790347581&mbox=target-global-mbox&mboxId=0&mboxMCSDID=60587E92DAC05908-78121EA30B6C0A5C&mboxURL=http%3A%2F%2Fwww.somewebsite.com%2Fsearch%2FSearchResults%3FES%3DResidentialShop%26Ntt%3Ddvr%2Bnot%2Bworking&mboxReferrer=http%3A%2F%2Fwww.somewebsite.com%2Fsearch%2FSearchResults%3FES%3DResidentialShop%26N%3D5538%26Ntt%3Ddvr%2Bnot%2Bworking&mboxVersion=58":"31x3,4z"},"s://www.xxxxxx.com/":{"home/":{"ak-cached/2h/styles/":{"common.css":"21ab,ej","myvzres2012.css":"21as,e6"},"commongh?ProcessClass=all&a=3&nocache=0.46050249505131435&scbReferrerURL=http://www.xxxxxx.com/search/SearchResults?ES=ResidentialShop&Ntt=dvr+not+working":"323t,cl"},"cs/groups/public/documents/adacct/oo_js.js":"31da,d5"}}}

**Comment by softwareklinic** [comment]
Below is how my graphite/statsd browser look like
![boomerang](https://cloud.githubusercontent.com/assets/7537289/16354038/521fe4b8-3a4c-11e6-9e24-a77d22c1399f.png)

**Comment by bluesmoon** [comment]
boomcatch is not compatible with the new compressed resource timing data we
send. Contact the boomcatch project and ask them to update.

**Comment by softwareklinic** [comment]
Sure - ive posted it on boomcatch - but in the meantime --- can i use some previous version of boomerang its not sending compressed resource timing data....

Or - can u point me to any resource on how can we implement any other type of beacon server.... and how to capture/process that data to either graphite or elasticsearch...

**Comment by bluesmoon** [comment]
I would recommend you implement the decompression algorithm from
https://github.com/nicjansma/resourcetiming-compression.js

**Comment by softwareklinic** [comment]
thank you - will check it out and try to get it in action

**Comment by bluesmoon** [comment]
You might want to pick up this thread on springernature/boomcatch#49

**Comment by softwareklinic** [comment]
Ty will do

Sent from my iPhone

On Jun 25, 2016, at 10:16 AM, Philip Tellis <notifications@github.com<mailto:notifications@github.com>> wrote:


You might want to pick up this thread on springernature/boomcatch#49<https://github.com/springernature/boomcatch/issues/49>
