### ISSUE TITLE
Usertiming API

### ISSUE THREAD

**Issue by softwareklinic** [SOASTA/boomerang#99]
Is the usertiming api now a part of boomerang??? Or do we need to include this separately and beacon the data separately?

**Comment by bluesmoon** [comment]
We haven't built it into a plugin yet, but it's quite simple to do. If you plan to do it, I'd suggest using @nicjansma's nicjansma/usertiming-compression.js to compress the results before adding it to the beacon.

You don't need to beacon the data separately, just add it to the existing beacon.

@nicjansma or @andreas-marschke I somehow remember someone working on a usertiming plugin but it doesn't seem to be part of our repo.  Any ideas?

**Comment by bluesmoon** [comment]
@querymetrics any suggestions/code that can be reused here?

**Comment by querymetrics** [comment]
@bluesmoon, @softwareklinic We have a WIP usertiming plugin here: https://github.com/SOASTA/boomerang/pull/77
Needs unit tests and documentation. I'll take another look at it soon.

**Comment by bluesmoon** [comment]
@softwareklinic try the pull request and see if it works for you

**Comment by nicjansma** [comment]
Closing via https://github.com/SOASTA/boomerang/pull/77
